### PR TITLE
Fixing Broken Link Because RNTester Changed Path

### PR DESCRIPTION
**Pull request by gedeagas**
This PR fix broken link on react-native-website because recently RNTester directory have been moved.

### CODE REVIEW

**Comment by gedeagas** [comment]
@Simek should we fix the broken link on versioned docs too?

**Comment by Simek** [comment]
> @Simek should we fix the broken link on versioned docs too?

Thank you for working on those updates! It would be nice if you can edit last versioned docs too (0.63). 🙂

**Comment by gedeagas** [comment]
@Simek updated.

**Review by Simek — APPROVED** [review]
Thank you! 👍

**Pull request merged**
