### PR TITLE
Renamed show/hide to toggle  in debugging section and remade gifs for both.

### PR DESCRIPTION
**Pull request by feargswalsh92**
Redo of #494 && #493 @charpeni.  WIll close #494

### CODE REVIEW

**Comment by charpeni** [comment]
Thanks! I'm just wondering where are the gifs?

**Comment by feargswalsh92** [comment]
Haha good spot, they didn't go through on my first commit for some reason, they're up there now!

**Comment by franzejr** [comment]
I think this can be merged, @kelset !

**Comment by feargswalsh92** [comment]
No worries I can fix that.

**Comment by feargswalsh92** [comment]
Ok I fixed that but I took another look and the yellow background of my terminal in this gif. 
image

**Comment by cpojer** [comment]
Closing because this went stale. Let me know if you wanna pick this back up and feel free to send a new PR.

**Pull request closed without merging**
