### PR TITLE
Update pillars-turbomodule.md

### PR DESCRIPTION
**Pull request by adamTrz**
Looks like script file was renamed some time ago so adjusting the docs :)

### CODE REVIEW

**Review by Simek — APPROVED** [review]
Nice catch, thank you for the correction! 👍

**Comment by thymikee** [comment]
Shouldn't we update versioned-docs as well? Seems like this is happening since 0.71. @adamTrz please confirm

**Comment by Simek** [comment]
Yup, it looks like it has been a part of 0.71 release:
* https://github.com/facebook/react-native/commit/97f5ef05e6396e9694e4b021e830b71c5900cd3c

@adamTrz Would you like to make an another PR for 0.71 doc?
* https://github.com/facebook/react-native-website/blob/main/website/versioned_docs/version-0.71/the-new-architecture/pillars-codegen.md

**Comment by adamTrz** [comment]
> Yup, it looks like it has been a part of 0.71 release:
> 
> * [facebook/react-native@97f5ef0](https://github.com/facebook/react-native/commit/97f5ef05e6396e9694e4b021e830b71c5900cd3c)
> 
> @adamTrz Would you like to make an another PR for 0.71 doc?
> 
> * https://github.com/facebook/react-native-website/blob/main/website/versioned_docs/version-0.71/the-new-architecture/pillars-codegen.md

https://github.com/facebook/react-native-website/pull/3526 :)

**Pull request merged**
