### PR TITLE
Replace 14 homepage 'showcase' brand images to scaled images (100x100)

### PR DESCRIPTION
**Pull request by elharony**
It's my first PR, so forgive me if it's not organized or something! 🙏 

I found that we are resizing the `Showcase` section images using CSS, which isn't recommended. Instead, we need to Use Scaled Images directly. It seriously affects our website performance, here's GTMetrix Report:
React-Native-Website-On-GTMetrix

I resized all images (without decreasing its quality nor changing its extension) to `100x100`. Total 14 images size was `574KB`, and now it becomes `81.3KB` (~86% smaller). This should give us a green `Grade A` on GTMetrix `Serve Scaled Images` criteria 👌 

UPDATE: I changed them to `100x100` instead of `68x68` as it appears to be hardcoded to `100x100` on the [Showcase Page](https://facebook.github.io/react-native/showcase), now it won't break the UI there.

### CODE REVIEW

**Comment by elharony** [comment]
Any updates, @rickhanlonii ?

**Comment by rickhanlonii** [comment]
@elharony, thanks for submitting this! 

On the left is your change and the right is production: 
Screen Shot 2019-11-11 at 9 55 55 PM

Switching to 100x100 causes blurring on retina screens, can you do this with 200x200 or 300x300? That should fix the blurring 👍

**Comment by elharony** [comment]
Thanks @rickhanlonii for checking it out and providing such feedback!

We can't switch them to 300x300 as many of them is less than 300x300, but 200x200 is good for all 14 images, except the `artsy`, it's `167x167`.

Well, I have a few suggestions here:
1. Stick with `150x150`, it will suit all current images & possibly future images as well.
2. Keep them `200x200` except the `artsy` logo as it will look even worse if we scale it up (Bigger size, Bad quality!)

What do you think, Ricky? I would be happy to continue working on this part according to your feedback/suggestion to make it scalable for any future images as well.

**Comment by rachelnabors** [comment]
What a wonderful idea! I have a suggestion: check out this format to accomodate retina screens as well as lower DPI without burdening one over the other:

```
<img 
  src="/img/2016/p_rachel-in-the-cubicle.png" 
  srcset="/img/2016/p_rachel-in-the-cubicle2x.png 2x" 
  height="338" width="600" alt="A manga-style illustration of Rachel Nabors winking from behind a computer monitor in an implied cubicle." 
/>
```
(From this [old blog post](http://rachelnabors.com/2016/10/06/microsoft/))

You would use:

```
<img 
  src="/img/100x100.png" 
  srcset="/img/200x200.png 2x" 
  height="100" width="100" alt="Brand X" 
/>
```

Unless you don't have a 200x200 pic, in which case this works fine:

```
<img 
  src="/img/100x100.png" 
  height="100" width="100" alt="Brand X" 
/>
```

What do you all think?

**Comment by rickhanlonii** [comment]
Sounds good to me! Sorry for the delay @elharony I must have missed the notification!

**Comment by elharony** [comment]
Great. So, I will go for #1 Suggestion and keep the in `150x150`, right @rickhanlonii ?

**Comment by rickhanlonii** [comment]
Oh sorry, my message is confusing, I think we should go with @rachelnabors' solution which is your option 1, along with the updated image tags she provided 👍

**Comment by rachelnabors** [comment]
Any movement on this @elharony? I'd soooo love to have this update on the site if you can get to it!

**Comment by rickhanlonii** [comment]
@elharony if you're not interesting in doing the full `` tag version, updating this to use you option number 2 of using 200x200 for all images except artsy is good too!

**Comment by rickhanlonii** [comment]
@orta do you know where we could find a artsy logo that's at least 200x200?

**Comment by elharony** [comment]
Hey @rickhanlonii ,

Very sorry for being late, I am doing a Frontend Diploma with OpenClassrooms and I had some projects to finish. I've done the requested update, please give it another try!

**Comment by orta** [comment]
Here's a copy: https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/70/64/3f/70643fc6-24c0-1878-c4a4-cbb92f8fc199/AppIcon-0-1x_U007emarketing-0-0-GLES2_U002c0-512MB-sRGB-0-0-0-85-220-0-0-0-4.png/460x0w.png

**Comment by elharony** [comment]
Thank you @orta . I've updated the `Artsy` logo. 
@rickhanlonii Now, all of them are updated to 200x200 and optimized. Let me know if this PR needs any further changes

**Comment by rickhanlonii** [comment]
Alright looks great thank you!

**Comment by rickhanlonii** [comment]
btw I just created this issue to update the Facebook logo if you're interested! 

https://github.com/facebook/react-native-website/issues/1524

**Comment by elharony** [comment]
Thanks for approving this PR. I am interested in #1524 and I will fix it! 👍

**Pull request merged**
