### PR TITLE
Add link to install instructions for emulators

### PR DESCRIPTION
**Pull request by alexkrolick**
The Quick Start doesn't mention where the instructions for running on emulators actually are in the docs; it's not obvious this means the tab at the top of the page.

### CODE REVIEW

**Comment by alexkrolick** [comment]
Ok, it's not showing in the deploy preview. Why not though...?

**Comment by charpeni** [comment]
Your changes are only applied to master (next version).

image

https://deploy-preview-197--react-native.netlify.com/docs/next/getting-started.html#now-what

**Comment by alexkrolick** [comment]
👍 thanks for that

Looks like it may require some JS to switch the tabs when switching within the page. I'll check it out later.

**Comment by cpojer** [comment]
Seems like this PR is stale so I'm going to close it.

**Pull request closed without merging**
