### PR TITLE
chore: add nativeID to image.md

### PR DESCRIPTION
**Pull request by nelsonprsousa**
Add nativeID prop to Image component, missing from the docs.

### CODE REVIEW

**Review by Simek — CHANGES_REQUESTED** [review]
Hi @nelsonprsousa, a you can see in the code `nativeID` is not a `Image` component prop, it's inherited from the `View` component:
* https://github.com/facebook/react-native/blob/master/Libraries/Image/ImageProps.js
* https://github.com/facebook/react-native/blob/master/Libraries/Components/View/ViewPropTypes.js#L457-L464

To avoid the large amount of code duplicates we usually placing the inherited props section with the link to the component at the top of the Props list, as seen in here:
* https://reactnative.dev/docs/scrollview#props

This part is definitely missing for the `Image` component right now. If you can, please update the PR code accordingly to the pattern mentioned above. Additionally if you want to see the changes in for example `0.64` docs, you will need to update also the versioned file under `website/versioned_docs`.

**Comment by nelsonprsousa** [comment]
> Hi @nelsonprsousa, a you can see in the code `nativeID` is not a `Image` component prop, it's inherited from the `View` component:
> 
> * https://github.com/facebook/react-native/blob/master/Libraries/Image/ImageProps.js
> * https://github.com/facebook/react-native/blob/master/Libraries/Components/View/ViewPropTypes.js#L457-L464
> 
> To avoid the large amount of code duplicates we usually placing the inherited props section with the link to the component at the top of the Props list, as seen in here:
> 
> * https://reactnative.dev/docs/scrollview#props
> 
> This part is definitely missing for the `Image` component right now. If you can, please update the PR code accordingly to the pattern mentioned above. Additionally if you want to see the changes in for example `0.64` docs, you will need to update also the versioned file under `website/versioned_docs`.

Hi @Simek ,
Just to be sure, you want me to remove the nativeID prop from Image and add this section to the Image.md just like the scrollview:
image

Right?

**Comment by Simek** [comment]
Yes, that's what I'm asking for! 🙂

**Comment by nelsonprsousa** [comment]
> Yes, that's what I'm asking for! 🙂

Done. Can you please re-check? 🙏 

Also, your opinion on [this](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51974) is also appreciated. Do you think I should change something here? It is related to this change.

**Comment by Simek** [comment]
> Also, your opinion on [this](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51974) is also appreciated. Do you think I should change something here? It is related to this change.

I think that all inherited props should be defined similar to the RN codebase, so the component props should be extended by parent props, like for example here:
* https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native/index.d.ts#L488

Since the DT file is quite large the links to the specific line don't work that good, there is the code I'm talking about:
```ts
export interface PressableProps extends AccessibilityProps, Omit<ViewProps, 'style' | 'hitSlop'>
```

Like in the example above, `Image` component props should be extended by `View` props omitting the `style`. This props diff also can be seen in the Flow annotation in the RN code:
* https://github.com/facebook/react-native/blob/master/Libraries/Image/ImageProps.js#L59

**Review by Simek — APPROVED** [review]
Thank you for the review updates! 👍

**Pull request merged**
