### PR TITLE
Update removing-default-permissions.md

### PR DESCRIPTION
**Pull request by MohamadKh75**
Removed old instructions!

### CODE REVIEW

**Comment by Simek** [comment]
Hi @MohamadKh75, can you explain the context of the removal? When does the permissions have changed? Did it affect all versions of Android or the specific ones?

**Comment by MohamadKh75** [comment]
Hey @Simek

**Reason:** As far as I know, those permissions moved to debug manifest so there aren't in the production build and therefore, no need to re-remove them! (maybe @cpojer can approve)

**When:** I can see the removal of `SYSTEM_ALERT_WINDOW` in this commit => https://github.com/facebook/react-native/commit/84a2fb0a4a67cd9dc37cf4e5bab814f25181cfb7
As you can see, it's mentioned all of `READ_PHONE_STATE`, `WRITE_EXTERNAL_STORAGE` and `READ_EXTERNAL_STORAGE` arent' need in debug nor production!

**Effect:** it will affect all versions.

**Comment by Simek** [comment]
@MohamadKh75 Thank you for the great, in-deep description! 👍 

The permission changes looks fine for me, but after removing most of the content the page became very short, I'm not sure if this should retain as a separate page, or should be placed as note or section elsewhere. 

What do you think @rachelnabors ?

> Maybe it should be good to add instruction (in a more tidy way) for users who want to remove android.vending.CHECK_LICENSE - If it is, let me know to push changes!

It would be nice if you can extend the guide or add the steps how to remove the permission.

**Comment by MohamadKh75** [comment]
@Simek 

I checked for `android.vending.CHECK_LICENSE` and it's not included by default so that's like the others!

I updated the docs and I guess it's too little for a page :smile:

**Comment by Simek** [comment]
> P.S.: Sorry to add more commits! I didn't have access to my laptop to clone and force push and I also don't know how to force push via GitHub web 😁

No problem, I will squash commit on merge anyway. 😄

**Comment by Simek** [comment]
> I updated the docs and I guess it's too little for a page 😄

@rachelnabors I have the similar feelings, what should be done in this situation? Can the content be added to the other existing page as new section?

**Review by rachelnabors — CHANGES_REQUESTED** [review]
I agree that it's too small as a standalone page! We can most likely deprecate/remove this page. Here's how we do it:

1) Decide if people need to know this information. If they do, when are they likely to need to know? Is there a guide for that (getting started, environment setup)? Where does this content fit in that guide.

2) Search the site for any links to this page. Do they matter now? Can they be removed? 

3) Remove the page from the sidebar.

4) (@Simek, weigh in here) Mark the page as deprecated or delete it outright.

**Comment by MohamadKh75** [comment]
> I agree that it's too small as a standalone page! We can most likely deprecate/remove this page. Here's how we do it:
> 
> 1. Decide if people need to know this information. If they do, when are they likely to need to know? Is there a guide for that (getting started, environment setup)? Where does this content fit in that guide.
> 2. Search the site for any links to this page. Do they matter now? Can they be removed?
> 3. Remove the page from the sidebar.
> 4. (@Simek, weigh in here) Mark the page as deprecated or delete it outright.

Hey
I guess:

1. we could remove the entire page (we can add the note to `AsyncStorage` docs!
2. I will try to find and send PRs
3 & 4 are for @Simek I guess :smile:

**Comment by Simek** [comment]
> we could remove the entire page (we can add the note to `AsyncStorage` docs!

`AsyncStorage` is a deprecated API, so I don't thinks so it's a good place. I think that the page from `Guides (Android)` group should be selected, because it's Android related only knowledge.

> 3 & 4 are for @Simek I guess 😄

Yeah, after the content will be moved I will remove the page from `docs` directory (next) and sidebar, but I will leave the versioned pages and I will add a note to the latest versioned page about the move.

**Comment by rachelnabors** [comment]
I'm not sure where in the Android docs it should live. @MohamadKh75 can you advise?

**Comment by Simek** [comment]
@rachelnabors Maybe the publishing page - https://reactnative.dev/docs/next/signed-apk-android - is a best place from the pages we currently have in there? There is no exact match, managing permission is somewhat related to the production build.

Other page that came to my mind is `PermissionsAndroid` API - https://reactnative.dev/docs/next/permissionsandroid. @MohamadKh75 what do you think?

> You don't need `WRITE_EXTERNAL_STORAGE` and `READ_EXTERNAL_STORAGE` permissions to use `AsyncStorage`.

@MohamadKh75 And I think that you were right and that the note quoted above should be added to the `AsyncStorage` 🙂

**Comment by MohamadKh75** [comment]
Well, we can move that note to both old `AsyncStorage` and `react-native-community/async-storage` docs!

**Comment by rachelnabors** [comment]
I'm into it! @MohamadKh75 would you update this PR accordingly?

**Comment by MohamadKh75** [comment]
> I'm into it! @MohamadKh75 would you update this PR accordingly?

done!

**Comment by cpojer** [comment]
@Simek said:
> Maybe the publishing page - reactnative.dev/docs/next/signed-apk-android - is a best place from the pages we currently have in there? There is no exact match, managing permission is somewhat related to the production build.

Could we remove the existing page and merge the content of the new version into the signed-apk-android page?

**Comment by Simek** [comment]
Closing in favor of #2327.

@MohamadKh75 I have added you as a co-author of that new PR, hope you are fine with that attribution, thank you for posting the initial changes! 🙂

**Pull request closed without merging**
