### PR TITLE
Add an ability to slide up announcement bar on scroll

### PR DESCRIPTION
**Pull request by Simek**
This PR adds an ability to slide up announcement bar on scroll (in a bit hacky, but working way). 

There were a lot of small UI/display glitches at the beginning, I have manage to fix most of them (I hope), but this solution is not ideal in any mean, it's just a temporary UX fix mainly for the small, mobile devices.

### Mobile preview
ezgif-1-fdf19ba5ebc8

### CODE REVIEW

**Comment by Simek** [comment]
@rickhanlonii I have updated the PR, but I'm not completely sure if this change is a good idea (especially for the desktop resolutions with height smaller than 900px - https://gs.statcounter.com/screen-resolution-stats/desktop/worldwide).

**Comment by rickhanlonii** [comment]
@Simek it's a fair concern, but I think on desktop it's still fine:

Screen Shot 2020-07-06 at 12 27 30 PM

**Comment by Simek** [comment]
@rickhanlonii I think it's fine until `SnackPlayer` fits on the screen:

Annotation 2020-07-06 183722

**Comment by rickhanlonii** [comment]
What's the issue there?

**Comment by Simek** [comment]
There is no issue on the screen. It's just a demonstration/clarification for the sentence above it.

**Pull request merged**
