### PR TITLE
Update discord logo

### PR DESCRIPTION
**Pull request by hackermondev**
Discord recently [updated their logo](https://blog.discord.com/how-were-making-discord-more-welcoming-for-everyone-ee152f198c60). This pull request removes the old logo in the showcase section and adds [the new logo](https://discord.com/branding).

Old:
image

New:
image

### CODE REVIEW

**Comment by Simek** [comment]
Hi @hackermondev, unfortunately it looks like Discord app icon colors are reversed. Background is Blurple and logo is white:
* https://apps.apple.com/us/app/discord-talk-chat-hang-out/id985746746
* https://play.google.com/store/apps/details?id=com.discord&hl=en&gl=US

**Comment by TheSavior** [comment]
This should probably be approved by someone from discord before we merge it

**Comment by hackermondev** [comment]
@Simek ah I couldn't find the logo with the blurple background on the website that's why I used the other logo but I'll change it.

**Comment by hackermondev** [comment]
new:

image

**Comment by jhgg** [comment]
> This should probably be approved by someone from discord before we merge it

yes this is fine :)

**Pull request merged**
