### PR TITLE
Updated button.md to reference Pressable instead of Touchable Opacity…

### PR DESCRIPTION
**Pull request by athakur3**
Updated button.md to reference Pressable instead of Touchable Opacity and TouchableWithoutFeedback

### CODE REVIEW

**Comment by athakur3** [comment]
> Hi @athakur3!
> 
> Thank you for your pull request and welcome to our community.
> 
> # Action Required
> In order to merge **any pull request** (code, docs, etc.), we **require** contributors to sign our **Contributor License Agreement**, and we don't seem to have one on file for you.
> 
> # Process
> In order for us to review and merge your suggested changes, please sign at https://code.facebook.com/cla. **If you are contributing on behalf of someone else (eg your employer)**, the individual CLA may not be sufficient and your employer may need to sign the corporate CLA.
> 
> Once the CLA is signed, our tooling will perform checks and validations. Afterwards, the **pull request will be tagged** with `CLA signed`. The tagging process may take up to 1 hour after signing. Please give it that time before contacting us about it.
> 
> If you have received this in error or have any questions, please contact us at [cla@fb.com](mailto:cla@fb.com?subject=CLA%20for%20facebook%2Freact-native-website%20%233237). Thanks!

Signed!

**Comment by leotm** [comment]
looks good @athakur3, just curious why recommend the new Pressable over TouchableOpacity or TouchableWithoutFeedback?

since TouchableOpacity or TouchableWithoutFeedback remain a simpler start
where we recommend Pressable for a more extensive approach

---

Capture

---

Capture2

**Comment by athakur3** [comment]
> looks good @athakur3, just curious why recommend the new Pressable over TouchableOpacity or TouchableWithoutFeedback?
> 
> since TouchableOpacity or TouchableWithoutFeedback remain a simpler start where we recommend Pressable for a more extensive approach
> 
> Capture
> 
> Capture2

@leotm You're right in saying that it's more extensive. But, going with the "future-proof" reference, I assume that we are eventually going to migrate to Pressable API. 
Hence this. Let me know if I'm wrong in my assumption.

**Comment by leotm** [comment]
gotcha ^ makes sense if that implies we're going to deprecate both, SWIM (Someone Who Isn't Me) will know

**Review by 3imed-jaberi — COMMENTED** [review]
+1  ✅

**Review by Simek — APPROVED** [review]
LGTM, thank you! 👍 

---

For the context, both of you have a valid points. Indeed, Pressable was created to replace all of the Touchables and Button in the long term, but because of its flexibility using Pressable requires a bit more code to be written to archive what Touchable give out-of-the box. So it's easier for the beginners to just use Touchables, without need to thinking about animation, state and interactions which need to be handled manually (this is also why we still use Touchables and Button in the docs examples way more often than Pressables). 

Currently we are at the state when all components are fine to use, and there is no hard deprecation notice on the Touchables and Button yet, but this might change in the future. You can read a bit more about reasoning behind Pressable in the blog post:
* https://reactnative.dev/blog/2020/07/06/version-0.63#pressable

**Comment by athakur3** [comment]
Yay! Thanks for merging that! My first open source contribution to Meta 😄

**Comment by Simek** [comment]
Welcome to the community! 🎉

**Pull request merged**
