### PR TITLE
📋 Clipboard - added snack examples [WIP] 👷🏽‍♂️👨🏽‍💻🕵🏽‍♂️

### PR DESCRIPTION
**Pull request by DaniAkash**
Belongs to https://github.com/facebook/react-native-website/issues/1579

Created snacks with both functional and class components. However, unable to get the snack working on the expo web player. Clipboard is implemented in react-native-web, hence could use a little help here...

Current issues preventing this PR from merging into the master:
- [ ] Unable to use clipboard on web snack 
  - Fix: Disabling web option in the snack (https://github.com/react-native-community/react-native-clipboard/issues/5) 
  - update: The above fix isn't the required fix ☹️

### CODE REVIEW

**Comment by rachelnabors** [comment]
I suspect it has to do with react native web: https://github.com/react-native-community/react-native-clipboard/issues/5

It's possible to configure it so the web version doesn't show in the Snack... `&supportedPlatforms=ios,android`

**Comment by rachelnabors** [comment]
Turns out React Native Web says it _does_ support the clipboard: https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/Clipboard/index.js

Can you investigate?

**Comment by DaniAkash** [comment]
> Turns out React Native Web says it _does_ support the clipboard: https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/Clipboard/index.js
> 
> Can you investigate?

I tried running it in my local expo-web setup and it was working fine, for some reason it is not working within the embedded player. Does the player share its clipboard with the system?

**Comment by rachelnabors** [comment]
Let me ask @brentvatne!

**Comment by rachelnabors** [comment]
Someone else submitted a Clipboard example. Let's drop it for now as it looks like the API is being deprecated. Thank you for your hard work!

**Comment by brentvatne** [comment]
in the web example, `getString()` will not work because the implementation it depends on is as follows:

https://github.com/necolas/react-native-web/blob/a7ab961d95de892e4b41c96ea945aa344fd49e50/packages/react-native-web/src/exports/Clipboard/index.js#L23-L25

`setString` should work, and it does in my tests using the same example code: https://snack.expo.io/@notbrent/clipboard-example

on ios and android things work as expected :)

**Pull request closed without merging**
