### PR TITLE
🔷🔹 Transforms 🔸🔶 - Added Snack Examples ▫️◻️⬜️

### PR DESCRIPTION
**Pull request by DaniAkash**
Belongs to https://github.com/facebook/react-native-website/issues/1579

Contains the Snack Examples and some details for using Transform style properties. 

However, the skew property on Android isn't working, so I'll mark it as a pending item.

Pending items in this PR:
- [ ] Skew transform not working on Android ☹️ https://github.com/facebook/react-native/issues/27649

### CODE REVIEW

**Comment by DaniAkash** [comment]
> So exhaustive! Thank you so _so_ much!! A few thoughts:
> 
>     1. I don't _normally_ ask to put styles inline (quite the opposite!), but here I think it might be handy to inline just the transform styles on the views they impact.
> 
>     2. What about moving the labels _inside_ the transformed objects? That would help associate the styles and explanations a little more closely!

Having styles inline will help here. I'll edit that!

But I'm kinda worried that putting the label inside the transforming boxes for skew & rotate transforms might make the text unreadable...

**Comment by rachelnabors** [comment]
@DaniAkash Hm... Give it a try? See how it looks!

**Comment by DaniAkash** [comment]
> @DaniAkash Hm... Give it a try? See how it looks!

I did and it looks kewl ✨

image

**Comment by rachelnabors** [comment]
I'm giving you bonus points for those cats. Take these diamonds!
harley-diamonds

**Pull request merged**
