### PR TITLE
Update pushnotificationios.md

### PR DESCRIPTION
**Pull request by r3nya**
Hello!

Looks like this part was accidentally deleted.

### CODE REVIEW

**Comment by Simek** [comment]
There is a PR for that #1330 (and an issue #1329) but both seems stale.

**Comment by r3nya** [comment]
Oh, thanks @Simek! Will close my PR.

**Comment by Simek** [comment]
@r3nya Oops... I had hope that this PR will be easier to merge for maintainers (due to some prettier issues in original PR) and I basically have put information above to create refs.

**Comment by r3nya** [comment]
@Simek oops^2. :)

**Comment by cpojer** [comment]
Actually let's merge the other one :)

**Comment by r3nya** [comment]
Okay :)

**Pull request closed without merging**
