### PR TITLE
Build.com blog post

### PR DESCRIPTION
**Pull request by gwmccull**
Thank you for the PR! Contributors like you keep React Native awesome!

Please see the Contribution Guide for guidelines:

https://github.com/facebook/react-native-website/blob/master/CONTRIBUTING.md

If your PR references an existing issue, please add the issue number below:

#<Issue>

Facebook blog post about the Build.com app written in React Native.  Worked with @axemclion

### CODE REVIEW

**Comment by hramos** [comment]
The Netlify preview does not quite handle images in the blog post. Have you built the website locally to ensure the image is loaded correctly?

**Comment by gwmccull** [comment]
@hramos yes, I checked it locally.  Thanks for looking at this!

screen shot 2018-03-20 at 3 36 42 pm

**Comment by gwmccull** [comment]
@hramos @axe-fb Do I need to do anything else for this branch to be merged?

Thanks

**Comment by gwmccull** [comment]
hi @hramos @axe-fb!

Checking in to see if there's a timeline for release

I'm excited to see this go live :-D

Thanks for all of your hard work!

**Comment by gwmccull** [comment]
@hramos :+1: thanks for the updates. They look good

**Pull request merged**
