### PR TITLE
Create geolocation.md

### PR DESCRIPTION
**Pull request by Hyllesen**
For some reason the geolocation.md file was no longer in repo, but was up on the website mentioning the now outdated navigator global.
#1151

### CODE REVIEW

**Comment by jamonholmgren** [comment]
I agree with @radko93 -- we need to point them to the community module which has been extracted.

**Comment by giacomocerquone** [comment]
I authored the #1151 issue.
What warning are you talking about? @radko93 Do you mean a warning while developing when requesting the old module? I'd say that sounds good too, but this is the react-native-website repo and I was asking for a way to include it in the docs and there are a couple of things I'm not getting.

1. How can that page be up if it's missing in this repo? Isn't the whole website built with netlify from this repo?
2. Where can I edit it then?

**Comment by radko93** [comment]
@giacomocerquone look at the warning here https://facebook.github.io/react-native/docs/webview

**Comment by giacomocerquone** [comment]
oh yes ok, thank you, I was just a little bit confused! I've also seen that this pr brings that warning! So nothing to do here 🙂

**Comment by cpojer** [comment]
Geolocation was removed intentionally as part of Lean Core. We should add it to the list of community modules, which should be done in a separate PR.

**Pull request closed without merging**
