### PR TITLE
Add 2021 banner survey

### PR DESCRIPTION
**Pull request by caabernathy**
Adding banner on front page for 2021 survey.

Screen Shot 2021-08-16 at 12 59 52 PM

Screen Shot 2021-08-16 at 12 59 21 PM

### CODE REVIEW

**Review by Simek — COMMENTED** [review]
Hi @caabernathy, what do you think about using Announcement Banner feature instead?

It content and appearance can also be customised:
* https://docusaurus.io/docs/api/themes/configuration#announcement-bar

You can see the example on the Docusaurus website. 🙂

**Comment by rachelnabors** [comment]
@Simek! Our hero! I was just swinging by to have a look at this and you've gone and provided a solution! Thanks so much!!

**Comment by rachelnabors** [comment]
New design is less attractive but still workable. I approve this
Screenshot 2021-08-16 at 23 38 29
Screenshot 2021-08-16 at 23 38 49

**Comment by rachelnabors** [comment]
Now with good styles!
Screenshot 2021-08-16 at 23 38 49
Screenshot 2021-08-10 at 16 39 39

**Pull request merged**
