### PR TITLE
add permission write access to node_module global

### PR DESCRIPTION
**Pull request by Arshiamidos**
flags added --unsafe-perm=true --allow-root

### CODE REVIEW

**Comment by Arshiamidos** [comment]
pls add this PR to hint other how install fast 
i searched many site to know this :)

**Comment by hramos** [comment]
Can you elaborate on how this helps others?

**Comment by Arshiamidos** [comment]
yes  
by default it can't install on mac straight forward .and when i searched for error i faced with many errors again :|
only by adding this flags i could install package wth admin previlage
i hope explain well

**Comment by charpeni** [comment]
Hmm, this looks more like an issue with your node installation and we should be fine without allowing root and running this with `sudo`.

Have you installed `node` with [brew](https://brew.sh/) or [nvm](https://github.com/creationix/nvm)?

**Comment by Arshiamidos** [comment]
if manual consist to install with **npm**,it must solve with **npm** .
but maybe we face another problem with __brew__ or __nvm__?
i think just hinting npm may be good solution
BTW it's not issue it's global hint with node.😉

**Comment by cpojer** [comment]
Thank you for your PR. I don't think we want to include this in the documentation at this time so I'm going to close this.

**Pull request closed without merging**
