### PR TITLE
Changed on submit editing

### PR DESCRIPTION
**Pull request by isa3bel**
Addresses #1459 In this PR, I removed a line that is false according to @natasha08n

### CODE REVIEW

**Comment by isa3bel** [comment]
the  language_lint failed since STYLGUIDE.md uses bad language as an example. I did not do this change.

**Comment by rachelnabors** [comment]
Could you rebase or merge with master? Should solve the issue as it has been fixed on master since :)

**Comment by isa3bel** [comment]
@rachelnabors are you referring to the language_lint failed test?

**Comment by isa3bel** [comment]
@rachelnabors so I should merge with master and then repush?

**Comment by isa3bel** [comment]
@rachelnabors I merged master into this branch and nothing seems to change?

**Pull request merged**
