### PR TITLE
docs: remove text running-on-device

### PR DESCRIPTION
**Pull request by luism3861**
this PR remove text, fix this issue #2941

### CODE REVIEW

**Review by Simek — CHANGES_REQUESTED** [review]
Hi @luism3861, thank you for the fix! 👍 

Can you also update the base doc file, located in `docs` directory?

**Comment by BattleOfPlassey** [comment]
> Hi @luism3861, thank you for the fix! 👍
> 
> Can you also update the base doc file, located in `docs` directory?

Here you go https://github.com/facebook/react-native-website/pull/2944

**Review by Simek — APPROVED** [review]
Let's merge this one, since we have another PR for unversioned docs. 🙂

**Comment by luism3861** [comment]
> Hi @luism3861, thank you for the fix! 👍
> 
> Can you also update the base doc file, located in `docs` directory?

hi @Simek  sorry for the late reply thanks for the update docs folder @BattleOfPlassey  :)

**Pull request merged**
