### PR TITLE
docs: update announceForAccessibility with queue

### PR DESCRIPTION
**Pull request by peterc1731**
This PR adds documentation for `announceForAccessibilityWithOptions`, added in https://github.com/facebook/react-native/pull/32637

### CODE REVIEW

**Comment by yungsters** [comment]
@Simek — Logistical question… when facebook/react-native#32637 is merged, do I need to wait before merging this?

**Comment by Simek** [comment]
@yungsters Depends on the timeframe, every case need an individual approach. Sometimes you need to wait even for the publish of next release, if upcoming version branch has been already cut, and PR has been merged only on `main`.

This is because `next` doc should always reflect the state of next release (`0.67` ATM), so additional or future changes need to wait until `next` will become the docs for their target release.

**Comment by yungsters** [comment]
So the PR has been merged to main, but 0.67 has already been cut. That means I have to wait until 0.67 is released before I can merge this, right?

cc @lunaleaps, @rachelnabors - This is an interesting point of coordination friction that can also lead to outdated docs, relevant to our discussion about keeping reference docs more up-to-date.

**Comment by peterc1731** [comment]
I've updated this to reflect the changes made when https://github.com/facebook/react-native/pull/32637 was merged

**Review by Simek — APPROVED** [review]
I have updated the docs for `0.68`, so this should b ready to ship.

Thank you @peterc1731, for the update in the first place! 👍

**Pull request merged**
