### PR TITLE
Add Image.getSizeWithHeaders documentation

### PR DESCRIPTION
**Pull request by se-bastiaan**
Thank you for the PR! Contributors like you keep React Native awesome!

Please see the Contribution Guide for guidelines:

https://github.com/facebook/react-native-website/blob/master/CONTRIBUTING.md

If your PR references an existing issue, please add the issue number below:

#<Issue>

### CODE REVIEW

**Comment by cpojer** [comment]
This doesn't seem to reflect the actual component at this time, so I'm closing this PR.

**Comment by se-bastiaan** [comment]
Isn't that what the waiting on PR label is for? The PR for changes in the actual component is still open: https://github.com/facebook/react-native/pull/18850.

Adding documentation is a part of the ['how to contribute'](https://facebook.github.io/react-native/docs/contributing#test-plan) and is the reason why this PR was still open.

**Comment by cpojer** [comment]
Woops, my mistake. Sorry I missed this one. Will reopen and then make a decision based on what we do with the PR to RN.

**Comment by se-bastiaan** [comment]
@cpojer I think the documentation would be relevant now. Not sure if the complete text is still relevant though.

**Pull request merged**
