### PR TITLE
Added onScrollBegin & EndDrag to the documentation

### PR DESCRIPTION
**Pull request by devofthings**
I didn't found anything about these possible actions in this documentation so I added them.
Some other people also had this problem:
https://stackoverflow.com/a/43859386

### CODE REVIEW

**Comment by devofthings** [comment]
Optional: Would be cool if you can tag this with the hacktoberfest-accepted label. If not its also not a problem I just wanted to improve the documentation again 😸

**Comment by charpeni** [comment]
Deploy preview for *react-native* ready!

Built with commit e68dcfdd46e42c6cec1ef6f5075f82f61d050ecf

https://deploy-preview-2265--react-native.netlify.app

**Comment by Simek** [comment]
Hi @devofthings, there are the [`VirtualizedList` component props](https://github.com/facebook/react-native/blob/master/Libraries/Lists/VirtualizedList.js#L1653), then `ScrollList` component inherits them and finally `FlatList` by itself. 

The props you are looking for are documented on the website in here:
* https://reactnative.dev/docs/next/scrollview#onscrollbegindrag

Unfortunately we do not list props inherited by the component, but lately, in `next` branch we have added the inherited props links to the TOCs so it should be easier to find those properties.

**Comment by devofthings** [comment]
@Simek Thats a strange rule but I understand it otherwise you guys need to track everything twice. The links will help! I guess this PR can be closed then?

**Comment by Simek** [comment]
@devofthings Thank you for understanding! 🙂 I can agree that we should think about handling the inherited props in a better way (but not multiply the maintaince work). I will try to sort this out a bit after the V2 migration, maybe we can use MDX fragments for those props.

**Pull request closed without merging**
