### PR TITLE
Changed require to import

### PR DESCRIPTION
**Pull request by Tahfimul**

### CODE REVIEW

**Review by cortinico — APPROVED** [review]

**Comment by Simek** [comment]
Hello @Tahfimul, thank you for the change! 👍 

Unfortunately we cannot merge your PR without the CLA sign. You can read more about it here:
* https://reactnative.dev/contributing/contribution-license-agreement

**Review by 3imed-jaberi — COMMENTED** [review]
+1

**Review by leotm — COMMENTED** [review]
good spot ^ would be good to update line 113 too

Capture

**Comment by cipolleschi** [comment]
@Tahfimul could you please sign the CLA and follow up with the suggested updates?

**Comment by Simek** [comment]
Closing, as the changes have been made in #3402.

**Pull request closed without merging**
