### PR TITLE
Update picker to be Removed since RN 0.66

### PR DESCRIPTION
**Pull request by cortinico**
Fixes https://github.com/facebook/react-native/issues/33763

### CODE REVIEW

**Comment by cortinico** [comment]
> and removing all newer docs files for the removed component/API.

Are you suggesting I remove the file from `main` and keep it versioned only for 0.66 with `*Removed.*`?

**Comment by cortinico** [comment]
> Yes, I think that removing this page for `0.67` and newer releases should be fine, but if you are not sure if it's a good idea we can ship the label change for now.

I don't have a strong opinion about this, I'm fine either way.

**Comment by Simek** [comment]
Let's remove the files then, we can always revert them back from latest versioned docs if needed. 🙂

**Comment by cortinico** [comment]
> Let's remove the files then, we can always revert them back from latest versioned docs if needed. 🙂

This is ready to go now @Simek 👍

**Pull request merged**
