### PR TITLE
Added SafeAreaView

### PR DESCRIPTION
**Pull request by birkir**
Adds SafeAreaView to the documentation.

I am not sure if we should add it to previous versions of React Native docs.

Here is the copy for now:

---

SafeAreaView
---

Render content within safe area boundaries of an device.

iOS: Renders nested content and automatically applies paddings reflect the portion of the view that is not covered by navigation bars, tab bars, toolbars, and other ancestor views. Moreover, and most importantly, Safe Area's paddings reflect physical limitation of the screen, such as rounded corners or camera notches (aka sensor housing area on iPhone X).

Android: Not applicable.

```javascript
<SafeAreaView style={{flex: 1}}>
  <View style={{flex: 1}}>
    <Text>Hello World!</Text>
  </View>
</SafeAreaView>
```

### Props

* [View props...](view.md#props)

### CODE REVIEW

**Comment by birkir** [comment]
https://deploy-preview-213--react-native.netlify.com/docs/next/safeareaview.html

**Comment by hramos** [comment]
Great find. It looks like [SafeAreaView first became available in v0.50](https://github.com/facebook/react-native/commit/983b05441d3d23809b924de2e4bf96a55c47428d#diff-93c50cbb21756c09e548f1992c350110), so I'd add it to that version.

I believe you should be able to achieve this by duplicating `docs/safeareaview.md` to `website/versioned_docs/version-0.50/safeareaview.md` and updating the markdown header to use the `version-0.50-` prefix (take a look at other versioned files to see how that works). You'd then need to update the sidebars for 0.50 and newer.

**Comment by birkir** [comment]
Thanks. I will add it to 0.50 and up!

**Comment by birkir** [comment]
https://deploy-preview-213--react-native.netlify.com/docs/0.50/safeareaview.html
https://deploy-preview-213--react-native.netlify.com/docs/0.51/safeareaview.html
https://deploy-preview-213--react-native.netlify.com/docs/0.52/safeareaview.html
https://deploy-preview-213--react-native.netlify.com/docs/0.53/safeareaview.html
https://deploy-preview-213--react-native.netlify.com/docs/safeareaview.html

All docs from 0.50 now have SafeAreaView page.

**Comment by hramos** [comment]
Beautiful. Thanks!

**Comment by birkir** [comment]
Synced with master

**Pull request merged**
