### PR TITLE
Update getting-started.md

### PR DESCRIPTION
**Pull request by MohamadKh75**
As [node-gyp](https://github.com/nodejs/node-gyp) supports Python 3, we can remove version 2 from docs.

cc @cpojer

### CODE REVIEW

**Comment by Simek** [comment]
Refs #2096 

Hi @MohamadKh75, since this guide has been updated lately please checkout the review comments and discussion about Python version in the PR linked above. If you sure that there are no other libraries or core parts that depends on Python 2, please test the clean setup on both macOS and Windows and provide the proof that it worked. We must be sure that this bump will not introduce any regression or problem for the users.

**Comment by MohamadKh75** [comment]
Hi @Simek

I just can confirm about android.

I asked @cpojer about this but it seems in your ref that it will cause problems for Windows users.

Maybe it should be good to separate sections for mobile and desktop :thinking:

**Comment by sunnylqm** [comment]
I think python is now totally unnecessary for windows platform. Just tested on a brand new windows 10 machine with only node installed, initiating is all good.

**Comment by Simek** [comment]
Closing in favor of #2250, thank you for the research. 🙂

**Pull request closed without merging**
