### PR TITLE
docs: update iOS runnning on simulator

### PR DESCRIPTION
**Pull request by luism3861**
this PR update iOS simulators according this PR https://github.com/react-native-community/cli/pull/1478

### CODE REVIEW

**Comment by luism3861** [comment]
> > Hi @luism3861,
> > it looks like your change have landed in cli @ `6.1.0`, while RN `0.66` uses cli @ `6.0.0` and it's not sure, when the cli package will be updated to the version which includes you change and which version of the package will be installed for the user.
> > For now, please revert `0.66` docs change and convert the PR to draft, until you can see the `6.1.0` or higher here:
> > 
> > * https://github.com/facebook/react-native/blob/main/package.json#L92
> 
> hi @Simek , thanks for the reply i change your suggestions

hi @Simek is the away to remove draft, https://github.com/facebook/react-native/blob/main/package.json#L92 package.json has updated

**Comment by luism3861** [comment]
> > Hi @luism3861,
> > it looks like your change have landed in cli @ `6.1.0`, while RN `0.66` uses cli @ `6.0.0` and it's not sure, when the cli package will be updated to the version which includes you change and which version of the package will be installed for the user.
> > For now, please revert `0.66` docs change and convert the PR to draft, until you can see the `6.1.0` or higher here:
> > 
> > * https://github.com/facebook/react-native/blob/main/package.json#L92
> 
> hi @Simek , thanks for the reply i change your suggestions

hi @Simek is there away to remove draft, https://github.com/facebook/react-native/blob/main/package.json#L95 package.json has updated

**Comment by luism3861** [comment]
> > > Hi @luism3861,
> > > it looks like your change have landed in cli @ `6.1.0`, while RN `0.66` uses cli @ `6.0.0` and it's not sure, when the cli package will be updated to the version which includes you change and which version of the package will be installed for the user.
> > > For now, please revert `0.66` docs change and convert the PR to draft, until you can see the `6.1.0` or higher here:
> > > 
> > > * https://github.com/facebook/react-native/blob/main/package.json#L92
> > 
> > 
> > hi @Simek , thanks for the reply i change your suggestions
> 
> hi @Simek it is time to remove draft?, https://github.com/facebook/react-native/blob/main/package.json#L95 package.json has been update.

**Comment by Simek** [comment]
Hi @luism3861, as you can see here - https://github.com/facebook/react-native/commit/848ba6fb1db81bbb44efd373af9e81f31f227aef - commit landed only on `main` branch, `0.68` is cut already, so we need to wait for the `0.68` to be release first.

**Comment by luism3861** [comment]
0.68 has been released  cc: @Simek

**Review by Simek — APPROVED** [review]
Thanks for the ping, let's ship it now :)

**Pull request merged**
