### PR TITLE
Add css for hover text on platform tags

### LINKED ISSUE #3047: iOS and Android tags are used, but not explained
## Description

The documentation makes liberal use of tags labelled 'iOS' and 'Android', without explaining the consequence of having a tag on some functionality.

## What is the problem?

As a beginner I'd like to read the documentation and understand what to do, what to expect. Currently, I just realize that a feature is related to iOS or Android, but I don't know enough to gain any insights.

## How can we address it?

Add a hover text or link that explains the meaning of the tag. Add a legend to the documentation that explains the meaning of tags (and other symbols) used.

## Why is it important?

The tag seems to convey important information, but as a beginner I don't understand what kind of information that might be.

## Who needs this?

New learners.

## When should this happen (use version numbers if needed)?

Examples:

* https://reactnative.dev/docs/activityindicator#hideswhenstopped-ios
* https://reactnative.dev/docs/statusbar#currentheight-android

### PR DESCRIPTION
**Pull request by apicgg**
Adds css for hover text which explains the platform tags (Android or iOS). This is a generic CSS rule which applies the style in every pages instead of manually adding `title` prop on each page.

closes #3047 

see #4116 

c/c @Simek

### CODE REVIEW

**Review by Simek — COMMENTED** [review]
Hello @apicgg, the currently proposed solution unfortunately has its flaws - it is hard to read, and overwrites the already existing content in `:::after` used for tag "cut-out" visualization. 

Screenshot 2024-06-02 082931

Those issues are the reason why I still would lead more toward new component or a 3rd party library, which can dynamically hooked up to DOM elements with certain classes on client side.

**Comment by apicgg** [comment]
Ah, I see now. I will try with your suggested approach as we were discussing earlier. 

Thanks for highlighting this.

I will convert this PR to draft now and will work on this.

**Comment by Simek** [comment]
Thank you for the willingness of putting a bit more time into solving this! 🙏 

If you have more questions about this feel free reach me out on Discord or via X DMs.

**Comment by apicgg** [comment]
@Simek I it okay for you to assign the issue #3047 to me?

**Comment by Simek** [comment]
> I it okay for you to assign the issue https://github.com/facebook/react-native-website/issues/3047 to me?

@apicgg Yes, I think that enough time has passed since the last activity of the previous person who volunteer, but you need to comment on the issue first. Otherwise I cannot do this, as per:
* https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users#about-issue-and-pull-request-assignees

**Pull request closed without merging**
