### PR TITLE
docs: Moving to use Announcement Banner for the Support Ukraine Initiative

### PR DESCRIPTION
**Pull request by dmitryvinn**
Summary
Following a suggestion in https://github.com/facebook/react-native-website/pull/2986, moving to use an announcement bar:
Screen Shot 2022-03-02 at 10 43 30 AM

### CODE REVIEW

**Comment by dmitryvinn** [comment]
Not sure why the deploy failed - it builds just fine on my local and the error message here doesn't seem related

**Comment by pushpender-singh-ap** [comment]
12:23:28 AM: API communication error. Canceling build. (Showing in Netlify Logs)

**Comment by yungsters** [comment]
@Simek, any ideas?

**Comment by leggomuhgreggo** [comment]
Very cool that the community is aiming to promote humanitarian aid!

Where should I direct suggestions that we should also add an option to support the people of Donbass?

Ya know -- just so it's clear that the community isn't supporting the puppet gov't installed after the US-directed coup in 2014?

If it's a question of need, I'd like to point out that 14k people have been killed as a result of the NATO/Ukranian onslaught against Donbass (which incidentally has been led in large part by IRL hitler-loving nazis)

Nothing but love to the people of Ukraine, but hope there's enough sense to realize there's nuance to the humanitarian dimensions here. 

Note: I made a similar [inquiry here](https://github.com/facebook/react-native-website/pull/2986) [[link from comment](https://twitter.com/consent_factory/status/1498257865693405185)] which was somewhat ungraciously responded to
Screenshot 2022-03-02 6 55 48 PM

**Comment by dmitryvinn** [comment]
Thank you, everyone, for your help in this initiative to support humanitarian causes in Ukraine. As we stated earlier, our mission at [Meta Open Source](https://opensource.facebook.com/) is to empower communities through open source. We believe that it means building a welcoming and safe environment for all. Adding this banner with a link to non-profits in Ukraine is another step towards that goal.

**Pull request merged**
