### PR TITLE
[Docs][New Guide Structure] Join props.md and state.md in the basics

### PR DESCRIPTION
**Pull request by ecreeth**
This is part of #929 

This PR remove `props.md` & `style.md` from `The Basics` section and are rolled into `Learn The Basics`

### TODO

- [x] ~delete~ `props.md`
- [x] ~delete~ `style.md`
- [x] remove `props.md` and `style.md` from sidebars
- [x] explain a little better what is happening in `HelloWorldApp`
- [x] add better state example using the Player
- [x] explain what the `props` are with links to reactjs.org 
- [x] explain what the `state` are with links to reactjs.org

### CODE REVIEW

**Comment by cpojer** [comment]
Nice! Can you work on the state section?

**Comment by ecreeth** [comment]
Of course, I'm going to finish it today!

**Comment by rachelnabors** [comment]
@ecreeth Great! Mind pulling down the latest from master and seeing if it fixes that language linting error?

**Comment by ecreeth** [comment]
@rachelnabors is done!

**Pull request merged**
