### PR TITLE
added documentation for `userSelect` prop to Text docs

### PR DESCRIPTION
**Pull request by dakshbhardwaj**
This PR adds documentation for `userSelect` prop to the text doc
Related to commit https://github.com/facebook/react-native/commit/fc42d5bbb9906c37c2f62d26c46f6e3191cccd01
and issue https://github.com/facebook/react-native/issues/34425

### CODE REVIEW

**Comment by dakshbhardwaj** [comment]
@Simek can you please review the PR?

**Review by Simek — CHANGES_REQUESTED** [review]
Can you add the default value to the table? Besides that everything looks fine. 👌

**Comment by dakshbhardwaj** [comment]
> Can you add the default value to the table? Besides that everything looks fine. 👌

Thanks for the review  @Simek . i have pushed down the changes

**Review by Simek — APPROVED** [review]
Thank you for the follow up! 🙏 Let's ship it!

**Pull request merged**
