### PR TITLE
Update Getting Started in Linux to reflect ANDROID_SDK bump

### PR DESCRIPTION
**Pull request by arushikesarwani94**
Updating Setting up the development environment in Linux documentation to reflect ANDROID_SDK version bump.

React Native is increasing the minimum ANDROID_SDK requirement from Android SDK Platform 31 to Android SDK Platform 33 for 0.72 onwards. Correspondingly changing the Android version. Updating our documentation to reflect the same as macOS & Windows

Found in https://github.com/facebook/react-native-website/pull/3605

### CODE REVIEW

**Review by Simek — APPROVED** [review]
LGTM! 🚀

**Review by cortinico — APPROVED** [review]
Thanks for fixing this 👍 Can we backport it also in the docs for 0.71?

**Comment by arushikesarwani94** [comment]
> Can we backport it also in the docs for 0.71?

Wasn't the whole point of this change that it's only needed 0.72 onwards ?

**Comment by cortinico** [comment]
> > Can we backport it also in the docs for 0.71?
> 
> Wasn't the whole point of this change that it's only needed 0.72 onwards ?

We bumped to SDK 33 inside 0.71, so all the references has to be updated in .71 and on main (.72)

**Pull request merged**
