### PR TITLE
Update accessibility related APIs

### PR DESCRIPTION
**Pull request by xuelgong**
This PR adds the new accessibility state in [facebook/react-native#24608](https://github.com/facebook/react-native/pull/24608) and accessibility value in [facebook/recat-native#26169](https://github.com/facebook/react-native/pull/26169). Also, clean up the accessibility APIs in View, Text and TouchableWithoutFeedback.

### CODE REVIEW

**Comment by cpojer** [comment]
@rachelnabors could you review this one? :)

**Comment by xuelgong** [comment]
@rachelnabors Thanks for the comments. I'll update the doc as you suggested.

**Comment by xuelgong** [comment]
@rachelnabors Could you help me merge this PR? Thanks!

**Comment by rachelnabors** [comment]
Wow! So it seems my Github notifications have been going to a blackhole account for sometime. Thank you so much for your patience!

I made some minor edits and structural changes. 

I am wondering, is there a reason these properties didn't get code examples?
- accessibilityIgnoresInvertColors(iOS)
- accessibilityRole (not sure we could do examples for ALL of them, but one would be nice!)
- accessibilityState (iOS, Android)
- accessibilityValue
- accessibilityViewIsModal
- accessibilityElementsHidden
- onAccessibilityTap
- onMagicTap
- onAccessibilityEscape

I feel like in the upcoming documentation restructuring, this might get split into several pages for readability—a properties reference, a testing guide, and most importantly: a how-to guide. 

Speaking of how-to guide, right now it's a bit difficult to see how all the pieces fit together. Is it possible to start the whole page with a bit of an explainer of why and how to go about making a component accessible? I feel like you do that with Accessibility Actions, but it's all the way below Accessibility Properties and doesn't cover the basics (like setting `accessible` to `true`). Is a wee sample tutorial at the top within scope for you? We can accept it the way it is now, but this would be such a help to future readers who want to make their apps accessible!

Thank you again so much for all your hard work on this!

**Comment by xuelgong** [comment]
@rachelnabors I am not the original author of this page so I don't know why not all the props have code examples. The purpose of this PR is to document the newly-added accessibility props - accessibilityState and accessibilityValue. So bigger refactoring on the doc is out of the scope of this PR. Could we merge this PR as it is now first? We have the plan to write up a guidance about how to make the component accessible and already start the work internally. We'll definitely contribute it back to the community when the doc is ready.

**Comment by rachelnabors** [comment]
Great, so glad someone is thinking ahead on the documentation! Please feel free to put us in touch! And thank you for contributing these docs!

**Pull request merged**
