### PR TITLE
Tweak home page example

### PR DESCRIPTION
**Pull request by gaearon**
1. Remove unused `Component` export.
2. `export default () => ...` is not recommended because it doesn't get a name. Changing this to an explicit assignment. Happy to change to `App` or whatever but this seemed clear enough.

### CODE REVIEW

**Comment by noway** [comment]
While we are at it, can we define `header` variable which is used in `style={header}`s too? It's not defined, the example won't run 😅

**Comment by gaearon** [comment]
>While we are at it, can we define header variable which is used in style={header}s too? It's not defined, the example won't run

What is it supposed to be?

**Comment by orta** [comment]
It can just be a fake import IMO `import {headers} from "./style"` or something like that maybe?

**Comment by noway** [comment]
agree with @orta, otherwise 
In https://github.com/facebook/react-native/blob/master/template/App.js it is defined as
```javascript
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: Colors.black,
  },
```
so it could be
```javascript
  const header = {
    fontSize: 24,
    fontWeight: '600',
    color: 'black',
  }
```
(replacing color to a string literal so that no extra dependency needed)

**Comment by orta** [comment]
Please don't _actually_ put the styles in - the point is that it looks and feels like the above screenshots. That it could be the implementation. Not that it is.

**Comment by kdawgwilk** [comment]
Do we want to mention "Fast Refresh" that isn't actually released yet?

**Pull request merged**
