### PR TITLE
Do not suggest users to 'Enable App Transport Security'

### LINKED ISSUE #3951: Docs out of date for "Publishing to Apple App Store"
### React Native Version

0.73

### Description

In https://github.com/facebook/react-native/pull/37923 we changed Info.plist to add `NSAllowsArbitraryLoads=false` and `NSAllowsLocalNetworking=true`. 

That means, [this section](https://reactnative.dev/docs/publishing-to-app-store#1-enable-app-transport-security) of the React Native docs are now out of date:

Screenshot 2023-12-11 at 4 28 40 PM

### Steps to reproduce

1. install new project
2. follow guide to publish to app store
3. see inconsistency 

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
no
```

### Stacktrace or Logs

```text
no
```

### Reproducer

no

### Screenshots and Videos

Above

### PR DESCRIPTION
**Pull request by cortinico**
Fixes #3951

This is no longer needed as the template sets those by default

### CODE REVIEW

**Comment by tarunrajput** [comment]
@cortinico, we should update these too 
https://github.com/facebook/react-native-website/blob/25498a4c343fd38f9351b6c045718a5570e60e49/docs/images.md?plain=1#L100-L103

https://github.com/facebook/react-native-website/blob/25498a4c343fd38f9351b6c045718a5570e60e49/docs/_integration-with-existing-apps-objc.md?plain=1#L329-L341

https://github.com/facebook/react-native-website/blob/25498a4c343fd38f9351b6c045718a5570e60e49/docs/_integration-with-existing-apps-swift.md?plain=1#L307-L319

**Comment by cortinico** [comment]
> @cortinico, we should update these too

Are you up for sending a PR with my commit + those changes so we can merge it?

**Comment by tarunrajput** [comment]
@cortinico, sure, I'll take care of it.

**Comment by rickhanlonii** [comment]
@cortinico @tarunrajput should we also tell people to remove `NSAllowsLocalNetworking`? That seems like a security risk, no?

**Comment by cortinico** [comment]
> @cortinico @tarunrajput should we also tell people to remove `NSAllowsLocalNetworking`? That seems like a security risk, no?

Seems reasonable. @cipolleschi what's your take on this?

**Comment by cipolleschi** [comment]
yup, I think that that's fine.

**Pull request merged**
