### PR TITLE
Add GitHub prettier check

### PR DESCRIPTION
**Pull request by johnf**
Prettier wasn't being run in CI

### CODE REVIEW

**Comment by johnf** [comment]
@cipolleschi Turns out prettier wasn't being run in CI

**Comment by cipolleschi** [comment]
Could you rebase on top of main? Your other changes have been merged, so we will isolate the changes on prettier here!

**Comment by johnf** [comment]
> Could you rebase on top of main?

Done

**Comment by Simek** [comment]
Prettier is run via ESLint and the preferable way would be to extend the setup to include `*.css/*.scss` files:
* https://github.com/facebook/react-native-website/blob/main/.eslintrc.json

The `theme` files are not re-formatted on purpose, since they are coming from the [Docusaurus Swizzle](https://docusaurus.io/docs/swizzling) mechanism, and unnecessary alterations makes an upgrade process more difficult.

**Comment by johnf** [comment]
@Simek Are you sure that eslint supports CSS or even SCSS files?
My research leads me to believe it doesn't.

For some background, I'm implementing this because when I submitted #4218, I followed the contributor instructions to run prettier and I noticed some issues.

@cipolleschi asked me to put them in a different PR, and we discovered that GitHub was not enforcing linting on CSS files.

I'll modify this PR now to exclude the autogenerated files from prettier.

I'm also happy to follow the eslint path, but I think it takes us down a stylelint path. But maybe that's going a bit far, with styling decisions made by an external contributor.

How would you like me to proceed?

**Comment by cipolleschi** [comment]
@Simek is the real expert here, so I'll defer the decision to them!

**Comment by Simek** [comment]
Okay, so I think I know that it's going on here, there is a lot of confusion due to the setup we have.

The concept of linting is to let people know about the code issues. The reason why any of Prettier checks are not run directly on the CI is conceptual - we don't want to automatically edit the files from PR branch on the CI, and that's what Prettier does (it just reformat code for you), while ESLint only warns you about the problem, unless you specifically want to use to to apply changes.

That's why I have referred to updating ESLint configuration instead. It should be possible via [`eslint-plugin-css`](https://github.com/ota-meshi/eslint-plugin-css), but due to SASS usage it might be tricky.

So the way forward I recommend is just to reformat SCSS files locally via command and commit them to the repo, without setting up the `prettier`direct usage on the CI.

**Comment by johnf** [comment]
@Simek It is possible to warn with prettier.
I've implemented this PR using prettier --check, this will exit with a status of 1 and list the files that have issues.
So if someone has forgotten to run prettier locally then the tests won't pass

**Pull request merged**
