### PR TITLE
Correct command to init with TS

### PR DESCRIPTION
**Pull request by SConaway**

### CODE REVIEW

**Comment by hramos** [comment]
Can you describe the motivation for this change?

**Comment by SConaway** [comment]
Sure: `npx react-native init AwesomeTSProject --template react-native-template-typescript` throws an error:
```
npx react-native init ts --template react-native-template-typescript
This will walk you through creating a new React Native project in /Users/steven/temp/ts
Using yarn v1.22.4
Installing react-native...
yarn add v1.22.4
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning react-native > fbjs > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning react-native > create-react-class > fbjs > core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning react-native > fbjs-scripts > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning react-native > metro-babel-register > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning react-native > @react-native-community/cli > mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning react-native > @react-native-community/cli > metro > mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning react-native > @react-native-community/cli > metro-config > metro-cache > mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning react-native > @react-native-community/cli > metro-core > jest-haste-map > jest-util > mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning react-native > @react-native-community/cli > metro-core > jest-haste-map > fsevents > node-pre-gyp > mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning react-native > @react-native-community/cli > metro-core > jest-haste-map > fsevents > node-pre-gyp > tar > mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-native > metro-react-native-babel-transformer@0.56.4" has unmet peer dependency "@babel/core@*".
warning " > react-native@0.61.5" has unmet peer dependency "react@16.9.0".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 411 new dependencies.
info Direct dependencies
└─ react-native@0.61.5
info All dependencies
├─ @babel/code-frame@7.8.3
...
(Tree shortened for this PR)
...
├─ y18n@3.2.1
├─ yallist@3.1.1
└─ yargs-parser@7.0.0
✨  Done in 18.98s.
info Setting up new React Native app in /Users/steven/temp/ts
info Fetching template react-native-template-react-native-template-typescript...
yarn add v1.22.4
[1/4] 🔍  Resolving packages...
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
error An unexpected error occurred: "https://registry.yarnpkg.com/react-native-template-react-native-template-typescript: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/steven/temp/ts/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
yarn remove v1.22.4
[1/2] 🗑  Removing module react-native-template-react-native-template-typescript...
error This module isn't specified in a package.json file.
info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.
warn Failed to clean up template temp files in node_modules/react-native-template-react-native-template-typescript. This is not a critical error, you can work on your app.
(node:90850) UnhandledPromiseRejectionWarning: Error: Command failed: yarn add react-native-template-react-native-template-typescript
    at makeError (/Users/steven/temp/ts/node_modules/execa/index.js:174:9)
    at /Users/steven/temp/ts/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async createFromRemoteTemplate (/Users/steven/temp/ts/node_modules/@react-native-community/cli/build/tools/generator/templates.js:115:5)
    at async createProjectFromTemplate (/Users/steven/temp/ts/node_modules/@react-native-community/cli/build/tools/generator/templates.js:88:3)
    at async generateProject (/Users/steven/temp/ts/node_modules/@react-native-community/cli/build/commands/init/initCompat.js:116:3)
    at async Object.initCompat (/Users/steven/temp/ts/node_modules/@react-native-community/cli/build/commands/init/initCompat.js:103:3)
(node:90850) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:90850) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

`npx react-native init AwesomeTSProject --template typescript` doesn't throw this error.

**Comment by Simek** [comment]
@hramos This change has a lot of history and it's confusing.

Everything started by issue #1537. Then #1668 was merged (`react-native-template-typescript`). After few days name has been changed in #1703 (`typescript`), and after another few day changed back in #1711 (`react-native-template-typescript`).

**Comment by rachelnabors** [comment]
@hramos @Simek rather than accepting and rejecting these issues over and over again, what is a better way to address the problem in the text?

**Comment by SConaway** [comment]
So what is happening here?

**Comment by Naturalclar** [comment]
@SConaway if you're getting the error that you mentioned in the comment above, you're likely to have an outdated version of the `react-native-cli` (either from older package of react-native itself, or from `@react-native-community/cli` < v2.)

There is a note in the website that mentions that

```
> **Note** If the above command is failing, you may have old version of `react-native` or `react-native-cli` installed globally on your pc. Try uninstalling the cli and run the cli using `npx`.
```

The underlying issue may be that the Note is not catching people's attention?

**Comment by SConaway** [comment]
Interesting. My `react-native-cli` is greater than v2.

Also, I didn't see that note either

**Comment by rachelnabors** [comment]
The note was only in the Next version of the docs. With 0.62's release, it is now in the main page. Let's see if this continues to be a problem.

**Pull request closed without merging**
