### PR TITLE
Update textinput.md

### PR DESCRIPTION
**Pull request by dragosbocancea**

### CODE REVIEW

**Review by Simek — COMMENTED** [review]
Hello @dragosbocancea, thank you for aupdating the docs! 👍 

Can you provide some context for this change?

**Comment by dragosbocancea** [comment]
> Hello @dragosbocancea, thank you for updating the docs! 👍
> 
> Can you provide some context for this change?

While trying to trigger a TextInput field to be autocompleted using a password manager, I have noticed that the former `autoComplete` did not do anything on android, but by replacing it to `autoCompleteType`, as suggested in one stackoverflow 
 post (if I remember correctly), it worked as desired. Therefore I supposed that the correct prop would be `autoCompleteType`, not `autoComplete`.

**Comment by dragosbocancea** [comment]
Up?

**Comment by Simek** [comment]
Unfortunately, I cannot confirm your changes with the React Native code. 

There is no entry name `autoCompleteType` when searching thought the whole repository:
* https://cs.github.com/facebook/react-native?q=autoCompleteType

The prop named `autoComplete` can be found in the `TextInput` JS file as well as in Android native code:
* https://github.com/facebook/react-native/blob/main/Libraries/Components/TextInput/AndroidTextInputNativeComponent.js#L125
* https://github.com/facebook/react-native/blob/main/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java#L758

**Pull request closed without merging**
