### PR TITLE
showcase adidas GLITCH app

### PR DESCRIPTION
**Pull request by istvanmakary**
Hey!

At POSSIBLE we've launched our application for Adidas in three countries in the past 1.5 years! The app is written entirely in RN and available on both iOS and Android.

Can you make it showcased?

### CODE REVIEW

**Comment by hramos** [comment]
Hi! We're not yet ready to accept new submissions. For reference, in the past we only added submissions that contained a deep technical article on how the app was built with React Native.

**Comment by istvanmakary** [comment]
hey @hramos!
There was a wrong link in my PR, sorry! 
Here is the deep technical architect, please take a look:
https://medium.com/possible-cee/how-we-have-been-breaking-patterns-with-the-adidas-glitch-d734340fd40e
Actually we wanted to be showcased a while ago, only this article was missing. Now I thought we could try agin.

Thanks for your time!

**Comment by hramos** [comment]
Can you add the app's icon to the assets folder and use that instead?

**Comment by istvanmakary** [comment]
hey @hramos!

Thanks to reopen my PR :) 
I have added the app icon to the asset folder!

**Pull request merged**
