### PR TITLE
fix: add missing icons to supported platforms

### PR DESCRIPTION
**Pull request by szymonrybczak**
Before:

CleanShot 2024-05-22 at 01 30 45@2x

After:

CleanShot 2024-05-22 at 01 27 48@2x

### CODE REVIEW

**Comment by Simek** [comment]
This is looking great, thanks for the additions! 🙏 

One small request - can we also move the `visionOS` before, `watchOS`, `Web` and `Windows` so the alphabetical order of platforms is retained?

**Comment by szymonrybczak** [comment]
> One small request - can we also move the visionOS before, watchOS, Web and Windows so the alphabetical order of platforms is retained?

Done ✅

**Review by Simek — APPROVED** [review]

**Comment by cortinico** [comment]
nit: Windows icon is not correct, we should be using this instead: https://fontawesome.com/icons/microsoft?f=brands&s=solid

**Comment by szymonrybczak** [comment]
> nit: Windows icon is not correct, we should be using this instead: https://fontawesome.com/icons/microsoft?f=brands&s=solid

ah, right. https://github.com/facebook/react-native-website/pull/4135

**Pull request merged**
