### PR TITLE
Backwards compatible docs fixes for docusaurus upgrade

### PR DESCRIPTION
**Pull request by darshkpatel**
This is with reference to the [Docusaurus v2 Upgrade](https://github.com/facebook/react-native-website/issues/2146
), attempting to reduce the final PR size.

I've fixed a few minor errors such as incorrectly closed tags, tags not being closed, JSX outside code blocks, etc.

These changes won't break the current docs deployment.

Edit: I've also fixed all the versioned docs these errors

### CODE REVIEW

**Comment by Simek** [comment]
@darshkpatel The changes affects the sidebar and title of deprecated pages right now:
Annotation 2020-08-20 103235

**Comment by darshkpatel** [comment]
Guess my dev server didn't update on change. Will revert the title changes

**Comment by darshkpatel** [comment]
@Simek Updated! Apologies for the oversight.

**Comment by Simek** [comment]
> @Simek Updated! Apologies for the oversight.

Not a problem at all, thank you for the great work and effort you put on the migration!

**Comment by Simek** [comment]
@darshkpatel There are some issues with tables and code blocks too:
* https://deploy-preview-2158--react-native.netlify.app/docs/asyncstorage#multimerge
Annotation 2020-08-20 140403

Is it necessary to wrap some of the Types column values in tables in the code block?

**Comment by darshkpatel** [comment]
> Is it necessary to wrap some of the Type column values in tables in the code blocks?

Yes, since the docs are expected to be MDX, it tries to parse it as a JSX code block and errors out

> Guess my dev server didn't pickup the changes. Will revert the title changes

I should start doublechecking with the netlify preview.

**Review by Simek — APPROVED** [review]
Thank you for cherry picking those changes! 👍

**Pull request merged**
