### PR TITLE
Update InteractionManager Documentation To Remove Notes About React Native Web Support

### PR DESCRIPTION
**Pull request by gedeagas**
This pull request focuses on removing the note concerning the support of the `InteractionManager` for the web platform in React Native documentation.

Furthermore, this update is driven by a strategic decision to segregate the documentation for InteractionManager across React Native and react-native-web. Such segregation is essential to ensure clarity and accuracy within the documentation. It is proposed that the specifics of InteractionManager support and functionalities within react-native-web be distinctly outlined in its exclusive documentation.

Related issues 
https://github.com/facebook/react-native-website/issues/3924

### CODE REVIEW

**Comment by Simek** [comment]
Hello @gedeagas, thanks for investigating this problem and providing a comprehensive description and context for it! :+1:

I agree with your take, and I think that it's a valid choice to remove the note from RN docs.

I would only have a small request to backport those changes to at least the latest versioned docs, before we ship it:
* https://github.com/facebook/react-native-website/tree/main/website/versioned_docs

Are you still interested in working on this contribution?

**Comment by gedeagas** [comment]
> Hello @gedeagas, thanks for investigating this problem and providing a comprehensive description and context for it! 👍
> 
> I agree with your take, and I think that it's a valid choice to remove the note from RN docs.
> 
> I would only have a small request to backport those changes to at least the latest versioned docs, before we ship it:
> 
> * https://github.com/facebook/react-native-website/tree/main/website/versioned_docs
> 
> Are you still interested in working on this contribution?

will do, will try to backport the changes. 

thank you @Simek

**Comment by gedeagas** [comment]
Hi @Simek,

I've just finished backporting the changes. Could you please review my PR again?

Thank you.

**Review by Simek — APPROVED** [review]
Looks great, thanks for the follow up! 👍

**Pull request merged**
