### PR TITLE
use [snack.io][PLAYER] instead of react-native-web-player 

### PR DESCRIPTION
**Pull request by ecreeth**
### Use `Snack.io` player instead of the `react-native-web-player` in the following sections.

Related issue #1131 

- [x] The Basics
- [x]  Guides
- [x] Guides (IOS)
- [x] Guides (Android)
- [x] Components
- [x] API

### CODE REVIEW

**Comment by brentvatne** [comment]
hmm that deploy preview seems wrong 🤔

**Comment by brentvatne** [comment]
hey @ecreeth, thanks for doing this! could you change SnackPlayer embeds to use `web` by default when they make sense on web? eg: most of the stuff in the the "basics" section except where we used SnackPlayer prior to this PR would make more sense with the `web` default.

to do this you can add it as an additional param for the code block:

```
```SnackPlayer name=Hello%20World&platform=web
```

**Comment by ecreeth** [comment]
Thank you for this! I was about to do it but I didn't know how 😄

**Comment by brentvatne** [comment]
looks good! @ecreeth - can you backport this to the 0.60 docs too? then I think it's ready to go!

**Comment by brentvatne** [comment]
hey @ecreeth! I rebased against master and changed every instance of ReactNativeWebPlayer to SnackPlayer in https://github.com/facebook/react-native-website/pull/1174, so let's continue there. Your commit attribution of course remains in place!

**Comment by ecreeth** [comment]
Great!!

**Pull request closed without merging**
