### PR TITLE
Update the screenshots in getting started page

### PR DESCRIPTION
**Pull request by apicgg**
Update and add some new screenshots in getting started page for macos with android and ios. It makes easy for newer developers to follow the set up instructions with screenshots.

### CODE REVIEW

**Review by cortinico — COMMENTED** [review]
I have to mention that I'm not a huge fan of adding those screenshots as they get stale really quickly (basically whenever we bump compile SDK version on Android)

**Comment by apicgg** [comment]
@cortinico Understood your POV. Thanks for the clarification.

**Review by cortinico — CHANGES_REQUESTED** [review]
Waiting for diff to update only `website/static/docs/assets/GettingStartedXcodeCommandLineTools.png` before we can merge this 👍

**Comment by apicgg** [comment]
> Waiting for diff to update only `website/static/docs/assets/GettingStartedXcodeCommandLineTools.png` before we can merge this 👍

Done.

**Review by cortinico — APPROVED** [review]

**Comment by apicgg** [comment]
@cortinico Does it look good to merge as well? Let me know in case.

**Pull request merged**
