### PR TITLE
Better component examples for DatePickerIOS and KeyboardAvoidingView

### PR DESCRIPTION
**Pull request by liamsheppard**
## Motivation
I had trouble when navigating the Docs working out what components were or how they worked. Sometimes the names can be a bit vague, for example, after building `<Picker>` into my project on iOS, the result was unexpected, I was actually wanting `ActionSheetIOS()`.

## Solution
Putting screenshots/gifs into the docs for each component to show how it works and, if applicable, how props effect the component. I am going to split this across a few PRs so that it doesn't become overwhelming or get overly stalled, and also to hopefully set a precedent for others to do the same.

## List of Fixes
- Added example code for `DatePickerIOS`
- Added example images/gifs for `DatePickerIOS` and props to demonstrate their behavior
- Added example gif for `KeyboardAvoidingView`
- Added a caveat to the `KeyboardAvoidingView` that I have noticed while developing personal projects
- Fixed a few broken links

### CODE REVIEW

**Comment by liamsheppard** [comment]
| DatePickerIOS | KeyboardAvoidingView |
| - | - |
|  |  |

**Comment by hramos** [comment]
Wow, this is very useful! Did you build the website and confirm that the assets are copied to the correct locations?

**Comment by liamsheppard** [comment]
^ Yep - confirmed. Although I had to manually copy the content into `versioned_docs` to render it on the website, I'm not sure if I'm doing something incorrectly?

**Comment by hramos** [comment]
That's fine - if you click on the version number at the top and choose "master", you should be able to see your changes without copying them into a versioned folder.

**Pull request merged**
