### PR TITLE
Update setup guide node version

### PR DESCRIPTION
**Pull request by Adnan-Bacic**
fix for: https://github.com/facebook/react-native-website/issues/3053

### CODE REVIEW

**Comment by Adnan-Bacic** [comment]
one thing i noticed when adding links to the LTS version of Node, was that most guides did not link to the Node download page.

linux docs link to: https://nodejs.org/en/download/package-manager/
and the expo docs linked to: https://nodejs.org/en/download/

however the rest of the react native cli docs dont link to the download page: https://nodejs.org/en/download/

i think this could also be a good addition.

**Comment by cortinico** [comment]
Thanks for doing this @Adnan-Bacic 👍 

I believe we should still add a number (i.e. Node 14). I agree that is a bit of a pain to maintain as we need to update it over and over as we bump it. But it will be easier for users and they won't have to open the Node Versions page to know which number was the previous LTS

**Comment by Adnan-Bacic** [comment]
i added the number so its more clear now.

one thing i noticed is that some values were refering to variables in external files, such as constants.packageManagers. and i found this file: https://github.com/facebook/react-native-website/blob/main/website/core/TabsConstants.js

would it make sense to add the minimum supported Node version as a variable somewhere, so that it would only have to be changed on place when it has to be updated?

**Review by cortinico — APPROVED** [review]

**Comment by cortinico** [comment]
Can I ask you to sign the CLA as requested by the github bot?

**Pull request merged**
