### PR TITLE
Initial draft of new Architecture Section containing renderer overview

### PR DESCRIPTION
**Pull request by rachelnabors**
In a future release, we're adding a new top level "Architecture" section to the site which will dive deep on how React Native works with conceptual overviews for library authors and contributors who want to grok RN. For now, this content lives in a "secret" section of the **/next** docs. This PR introduces:

* "Secret" architecture section with [overview page](https://deploy-preview-2892--react-native.netlify.app/docs/next/architecture-overview)
* Page on [Rendering in React Native](https://deploy-preview-2892--react-native.netlify.app/docs/next/rendering)
* Page about how [React Native rendering changes with Fabric](https://deploy-preview-2892--react-native.netlify.app/docs/next/fabric-renderer) (mentions of "Fabric" should link to this page)
* Page about [how rendering works under the hood](https://deploy-preview-2892--react-native.netlify.app/docs/next/rendering-implementation)
* [Glossary](https://deploy-preview-2892--react-native.netlify.app/docs/next/glossary) of common terms used in the new docs which will expand as we expand the section

This is a hack job of an original, longer piece, to cut it into more digestible, organized pieces. Here's what it still needs from its author and editorial:
### Images:
- [x] Images! Didn't have the source images
- [x] Render/commit/mount diagrams

### Pages:
- [x] Putting something down for "Architecture Overview"
- [x] [Fabric page](https://deploy-preview-2892--react-native.netlify.app/docs/next/fabric-renderer) needs to be edited into more than just a pile of bullet points. Finesse the first paragraph to share this context "Officially in 2021 a suite of feactures came together.. etc"
- [x] Editing the opening sections to explain "what this doc will tell you and why you might care" a little better (re: adding context that these docs are discussing about the new architecture Fabric and link to the "Fabric Page") @lunaleaps 
- [x] Wordsmithing the page titles 
- [x] Resize images in threading-model.md

### Glossary:
- [x] Interlinking the pages better (terms to the glossary, mentions of Fabric to the [page about Fabric](https://deploy-preview-2892--react-native.netlify.app/docs/next/fabric-renderer))
- [ ] Glossary, format and double-check (re:  "mount phase", etc CC @gaearon)

### CODE REVIEW

**Comment by Simek** [comment]
Can you revert the changes to the `yarn.lock`? There are a lot of removals in there which seems to be not related to the other changes in this PR. :)

**Comment by lunaleaps** [comment]
Threading Model PR: https://github.com/facebook/react-native-website/pull/2897

**Comment by lunaleaps** [comment]
xplat-implementation: https://github.com/facebook/react-native-website/pull/2898/files

**Comment by lunaleaps** [comment]
PR for view-flattening: https://github.com/facebook/react-native-website/pull/2899

**Comment by lunaleaps** [comment]
@Simek I took a look at the yarn.lock changes and it seems like `main` has some yarn updates, will keep the changes in for now

**Review by sammy-SC — APPROVED** [review]
looks great!

**Pull request merged**
