### PR TITLE
Remove mention of unused ( ) => syntax from tutorial

### PR DESCRIPTION
**Pull request by elitree**
A previous revision of this document had removed usage of ( ) => in the example code, but it's still mentioned in the ES2015 features sentence as appearing in the example. The mention of ( ) => in that sentence should be removed.

Thank you for the PR! Contributors like you keep React Native awesome!

Please see the Contribution Guide for guidelines:

https://github.com/facebook/react-native-website/blob/master/CONTRIBUTING.md

If your PR references an existing issue, please add the issue number below:

#<Issue>

### CODE REVIEW

**Comment by elitree** [comment]
Thanks--I just wanted to clarify that one sentence on the initial tutorial page, because I kept reading it and going back to the code example expecting to see the arrow function, so it was confusing for me. No worries if you think it should stay in there, thanks.

**Comment by charpeni** [comment]
Now that I'm reading it again and again, it may be confusing. Let me think about this one.

**Comment by elitree** [comment]
Thanks for your help!

**Comment by charpeni** [comment]
Thanks for yours!

**Pull request merged**
