### PR TITLE
Solved #1921 . All the functions and exports in all the doc file and made to new standard

### PR DESCRIPTION
**Pull request by psjishnu**

### CODE REVIEW

**Comment by psjishnu** [comment]
Every file that has exports and functions are converted to the new standard .

**Comment by Simek** [comment]
Hi @psjishnu, thank you for contributing to the standardization efforts! Can you tell me which work batch/batches (from the #1921) is this PR covering?

**Comment by psjishnu** [comment]
I have standardized all the functions in the docs

**Comment by psjishnu** [comment]
> @Simek  I have standardized all the functions in the docs

**Comment by psjishnu** [comment]
@Simek I just changed every  file with old standards

**Comment by Simek** [comment]
@psjishnu Ah, I'm sorry, but since it's stated in the issues that you should post the comment with selected batch/batches before you start you work I had to ask you to discard the files that are a part of other accepted PR or from work batches taken by others.

It's not stated in the issue explicitly, but it would be nice to avoid the inline exports for the `class`es too (Class Component version of examples). Other PRs contains such changes.

**Comment by psjishnu** [comment]
OK sir , I will open PR in required manner

**Comment by Simek** [comment]
@psjishnu Quick question, just to be sure: Are you going to post modified PR for all of the remaining batches or should I unassign you from some of them?

**Comment by psjishnu** [comment]
@Simek  I have opened another PR excluding files tat have changes which are a part of another PRs

**Pull request closed without merging**
