### PR TITLE
Update barStyle enum prop description on StatusBar component

### PR DESCRIPTION
**Pull request by matheussss1**
The barStyle description with 'Light/Dark background' confuses, because the prop does not change the background color

### CODE REVIEW

**Comment by cortinico** [comment]
Could you sign the CLA?
Also are you sure about this change, as iirc it does indeed change the background on Android API >= 23?

**Comment by matheussss1** [comment]
> Could you sign the CLA? Also are you sure about this change, as iirc it does indeed change the background on Android API >= 23?

As far as i know, the StatusBar componente does have a backgroundColor prop that is only available to Android.
The barStyle props is only about changing the text color of the StatusBar.

**Comment by matheussss1** [comment]
@cortinico any update?

**Review by cortinico — APPROVED** [review]

**Comment by matheussss1** [comment]
> Can you fix the lint @matheussss1

fixed

**Review by Simek — APPROVED** [review]
Thanks for the updates and lint fix, LGTM! 👍

**Pull request merged**
