### PR TITLE
Add Brex to the app showcase

### PR DESCRIPTION
**Pull request by derekstavis**
Adding Brex to the React Native app showcase list!

### CODE REVIEW

**Review by Simek — APPROVED** [review]
Hey Derek, thank you for working on this PR! 🙏 

LGTM, but let's wait for another review before we ship it.

**Comment by cortinico** [comment]
Hi @derekstavis 
Thanks for sending this over. Applications to be added to the showcase page go over the form that is at the bottom of this page: https://reactnative.dev/showcase

I see Brex already applied there some weeks ago. Let me bump this up as we have several others in the backlog and we'll get back to you

**Comment by derekstavis** [comment]
Any updates on this? 😬

**Comment by kmiddleton14** [comment]
Thanks @derekstavis! We've reviewed your request and appreciate the PR! Let us know if you plan on writing about Brex's usage of React Native so we can add it as part of the "Learn More"

**Pull request merged**
