### PR TITLE
[TextInput] Add notes about `passwordRules`

### PR DESCRIPTION
**Pull request by retyui**
Preview: https://deploy-preview-2124--react-native.netlify.app/docs/next/textinput#passwordrules

### CODE REVIEW

**Comment by Simek** [comment]
Hi @retyui, can you provide the context for the introduced changes or the source issue from the main repository?

**Comment by retyui** [comment]
passwordRules really "unbelievable to" to test when you don't under what conditions the operating system shows the dialog

you need to take into account many circumstances ( iCloud Keychain + Autofill )

**Comment by retyui** [comment]
@Simek

**Comment by retyui** [comment]
Thanks

**Pull request merged**
