### PR TITLE
🎶 LayoutAnimation 🕺🏽 - Added Snack Examples - WIP 👷🏽‍♂️🏗

### PR DESCRIPTION
**Pull request by DaniAkash**
Belongs to https://github.com/facebook/react-native-website/issues/1579

Contains the snack with both functional & class component example for LayoutAnimations. Since LayoutAnimations have both inbuilt and custom config, this documentation requires two examples. One for inbuilt presets and another one for creating our own animation config. 

The following checklist tracks the completion of both examples
- [x] InBuilt Presets
- [ ] Custom config

### CODE REVIEW

**Comment by rachelnabors** [comment]
@DaniAkash I'm loooooving your example! I just got a PR that turns the old example into a hooks-based Snack up and running #1593 and was wondering if you'd be able to combine the two? Personally, I feel the more examples the better.

How is the custom config example going?

**Comment by DaniAkash** [comment]
> @DaniAkash I'm loooooving your example! I just got a PR that turns the old example into a hooks-based Snack up and running #1593 and was wondering if you'd be able to combine the two? Personally, I feel the more examples the better.
> 
> How is the custom config example going?

I just got a great idea! I'll rebase my branch with this PR and add more details. I'll be updating this PR real soon 👍

**Comment by rachelnabors** [comment]
I can't wait, @DaniAkash!

**Comment by DaniAkash** [comment]
Not sure what happened here... I just rebased my PR with the current master 

chaos

**Comment by DaniAkash** [comment]
@rachelnabors I think I'll raise a new PR...

leaving

**Comment by DaniAkash** [comment]
Closing it in favour of https://github.com/facebook/react-native-website/pull/1721

**Pull request closed without merging**
