### PR TITLE
Add styling to the "Native Code Required" banners

### LINKED ISSUE #1839: There's a banner that looks like a regular paragraph—style it
As per #1835, we seem to have a class `banner-native-code-required` used to alert people to the possible need to eject their Expo projects scatter throughout the site—but the warnings blend in (a little awkwardly) with the surrounding text. These should be made to stand out. Here are all the pages using it: https://github.com/facebook/react-native-website/search?q=banner-native-code-required&unscoped_q=banner-native-code-required

Heads up to @brentvatne

### PR DESCRIPTION
**Pull request by Simek**
Fixes #1839.

This PR adds styling to the "Native Code Required" banners across the all docs. The color has been selected from the few mockups which all were based on the colors from React Native schemes and images ([example](https://reactnative.dev/docs/intro-react-native-components#views-and-mobile-development)). The design was based on the currently widely used note/quote boxes.

Expo logo file has been taken from the Expo [branding](https://expo.io/brand) page.

### Preview
Annotation 2020-05-11 200127

### CODE REVIEW

**Comment by rachelnabors** [comment]
I love it! It's good that we are finally styling these call outs! One thought: @brentvatne might have opinions on the colors—we had a violet option, but went with pink to draw more attention. Let me grab his eyes!

**Comment by Simek** [comment]
Bottom banner has a different content because it was the initial version based on the Expo color (the rest of mocks are based on the colors from the RN images/resources):
nativebox

@brentvatne It would be nice to have official Expo logo also in SVG format.

**Comment by brentvatne** [comment]
This is great @Simek! I love that it links folks out to the relevant page from the Expo documentation to help eliminate any confusion.

I think the purple one (or as we say at Expo, blurple) is my favourite! The others (except the red) are good too.

SVGs are here: https://github.com/expo/logos. I believe logo type A is the one you're looking for: https://github.com/expo/logos/blob/master/svg/logo-type-a.svg

**Comment by rachelnabors** [comment]
@brentvatne I favor the violet since we use it as a secondary color in other parts of the docs. I am curious why violet says "error" more than blurple? We can go with the pink if it's a blocker

**Comment by brentvatne** [comment]
@rachelnabors - gotcha! I wanted to ensure it wasn't used in other context along with an "🚨🚨🚨 Error!" type message and it seems like it's not so I defer to your judgement on what is most effective and aesthetic!

**Pull request merged**
