### PR TITLE
fix text in hamburger menu for mobile devices

### PR DESCRIPTION
**Pull request by luism3861**
this PR fix style text in hamburger menu for different devices.

Before:
image

After:
image

@Simek i test for different iphone sizes and android and looks better!:

### CODE REVIEW

**Comment by luism3861** [comment]
cc: @Simek

**Comment by luism3861** [comment]
@Simek could you take a look for this PR?

**Comment by Simek** [comment]
Hi @luism3861, thank you for working on this!

I think that adding a viewport breakpoint and changing `navbar-sidebar` size on very small screens is bit more universal solution that adding bunch of overwrites for `navbar-sidebar` children. I have also switched the media breakpoint to the lowest value already used in the styles which is `480px`.

To be honest I don't like the navbar transformation and how the mobile menus are implemented in Docusaurus right now. There are two menus, one for navigation content and other for the sidebar content, also the ToC content is missing, which is a bit confusing to the users. But it looks like the refactor/improvement is already in progress:
* https://github.com/facebook/docusaurus/pull/4273

**Comment by luism3861** [comment]
> Hi @luism3861, thank you for working on this!
> 
> I think that adding a viewport breakpoint and changing `navbar-sidebar` size on very small screens is bit more universal solution that adding bunch of overwrites for `navbar-sidebar` children. I have also switched the media breakpoint to the lowest value already used in the styles which is `480px`.
> 
> Please confirm if the mobile menu works for you correctly now (after the size change), after confirmation I will merge the changes, if there will be no issues with changed solutions.
> 
> Also to be honest I don't like the navbar transformation and how the mobile menus are implemented in Docusaurus right now. There are two menus, one for navigation content and other for the sidebar content, also the ToC content is missing, which is a bit confusing to the users. But it looks like the refactor/improvement is already in progress:
> 
> * [facebook/docusaurus#4273](https://github.com/facebook/docusaurus/pull/4273)
> 
> ### Preview
> Screenshot 2021-05-24 at 13 55 44

hi @Simek  thank you for the review , after test for all mobile devices looks better with, `width: 100% ` in media querie `480px` you can merge this . yeah for me i don't like the navbar, i hope to merge the new PR for the new navbar

**Pull request merged**
