### PR TITLE
website: update networking examples 

### PR DESCRIPTION
**Pull request by luism3861**
this PR update network examples, i think looks better refactor with async await!.

### CODE REVIEW

**Review by Simek — COMMENTED** [review]
Hi @luism3861, thank you for the refactor! 👍 

I like this change, but unfortunately I cannot test it right now because the example is not working on PROD nor the deployment preview due to the CORS error:

Screenshot 2021-07-13 110302

I will need to fix this issue first, before I can accept your change, sorry about that!

**Comment by Simek** [comment]
@luism3861 The CORS issue should be fixed now, can you update the PR branch, so we can test the changes via preview deploy? 🙂

**Comment by luism3861** [comment]
> @luism3861 The CORS issue should be fixed now, can you update the PR branch, so we can test the changes via preview deploy? 🙂
 
hi @Simek i updated all new changes from `master` branch it's ready to be merge!. :)

**Review by Simek — APPROVED** [review]
LGTM, thank you for the branch update! 🙂

**Pull request merged**
