### PR TITLE
fix(#3969): overflow table heading text in TextInput section

### PR DESCRIPTION
**Pull request by varsha1209**

### CODE REVIEW

**Review by Simek — COMMENTED** [review]
Hello @varsha1209, thank you for reporting this issue and posting a fix! 👍 

Can you also apply changes to other [versioned docs](https://github.com/facebook/react-native-website?tab=readme-ov-file#versioned-docs) and unversioned file located in [`docs` directory](https://github.com/facebook/react-native-website/tree/main/docs) in the workspace root?

**Comment by varsha1209** [comment]
Screenshot 2024-01-03 151418

**Comment by varsha1209** [comment]
> Hello @varsha1209, thank you for reporting this issue and posting a fix! 👍
> 
> Can you also apply changes to other [versioned docs](https://github.com/facebook/react-native-website?tab=readme-ov-file#versioned-docs) and unversioned file located in [`docs` directory](https://github.com/facebook/react-native-website/tree/main/docs) in the workspace root?

Done

**Comment by Simek** [comment]
@varsha1209 Looks like the newest commit is empty, and changeset only includes initial file edit.

**Comment by varsha1209** [comment]
> @varsha1209 Looks like the newest commit is empty, and changeset only includes initial file edit.

I have added the changes, but they're not appearing here.

**Comment by Simek** [comment]
Can you prepare separate PR with missing changes then? And we can merge both when ready.

**Review by Simek — APPROVED** [review]
Let's ship this changeset, I will work on the backports soon. 

Thank you for the contribution! 👍

**Pull request merged**
