### PR TITLE
Fixes link to cheatsheet

### PR DESCRIPTION
**Pull request by zomars**

### CODE REVIEW

**Comment by rachelnabors** [comment]
Could you rebase or merge with master? Looks like master was having some problems with a CI test when you branched it!

**Comment by zomars** [comment]
@rachelnabors it is done!

**Comment by rachelnabors** [comment]
Ah, so, @zomars, it looks like your PR now touches 63 pages? Looks like the merge didn't go as intended! Can you revise to just PR the one page?

**Comment by zomars** [comment]
Oh boy... I  think I got it now 😅

**Pull request merged**
