### PR TITLE
Fixed a minor typo

### PR DESCRIPTION
**Pull request by Ashikpaul**
Related to #2037

### CODE REVIEW

**Comment by Simek** [comment]
@Ashikpaul Thank you for updating the versioned docs! Next time please add the commits to the PR, where changes were requested. 😄

**Comment by Ashikpaul** [comment]
Sorry @Simek, I didn't understand. Could you please explain?

Thank you

**Comment by Simek** [comment]
@Ashikpaul Instead of creating new Pull Request you should update the existing one (#2037). If you not familiar with adding commits to the existing PR you can follow [GitHub guide](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork). You can alternatively use [GitHub Codespaces](https://github.com/features/codespaces/) (if you have an access). I can also recommend reading through the [Contibutors guide](https://github.com/facebook/react-native-website#-contributing) in the Readme which covers the basic steps when working with local copy of repository.

**Comment by Ashikpaul** [comment]
Oh, I didn't know we could do that. Thank you so much😍

**Pull request merged**
