### PR TITLE
fix : Getting started in Mac to reflect Android version

### PR DESCRIPTION
**Pull request by arushikesarwani94**
Updating Setting up the development environment in MacOS documentation to reflect Android version bump.

React Native is increasing the minimum ANDROID_SDK requirement from Android SDK Platform 31 to Android SDK Platform 33 for 0.72 onwards. Updating our MacOS documentation to reflect the same for corresponding Android version.

#3605

### CODE REVIEW

**Review by Simek — APPROVED** [review]
Thank you for the update, LGTM! 👍

**Review by cortinico — APPROVED** [review]
Great stuff 👍 Can we backport it to 0.71 docs also?

**Comment by arushikesarwani94** [comment]
> Can we backport it to 0.71 docs also?

Wasn't this change only applicable for the 0.72 ?

**Comment by cortinico** [comment]
> > Can we backport it to 0.71 docs also?
> 
> Wasn't this change only applicable for the 0.72 ?

Nope that's applicable for both as we bumped to SDK 33 in .71

**Comment by arushikesarwani94** [comment]
https://github.com/facebook/react-native-website/pull/3616 ✅

**Pull request merged**
