### PR TITLE
update Flatlist examples with arrow functions

### PR DESCRIPTION
**Pull request by luism3861**
this pr only update both examples with arrow functions

### CODE REVIEW

**Comment by rachelnabors** [comment]
We're actually going to standardize to `function()` syntax because it seems more widely used in training materials as well as some issues with ESLint and Prettier.

**Comment by luism3861** [comment]
> We're actually going to standardize to `function()` syntax because it seems more widely used in training materials as well as some issues with ESLint and Prettier.

ok rachel can i take some examples and convert with functions ?

**Comment by luism3861** [comment]
> > We're actually going to standardize to `function()` syntax because it seems more widely used in training materials as well as some issues with ESLint and Prettier.
> 
> ok rachel can i take some examples and convert with functions ?

@rachelnabors

**Comment by rachelnabors** [comment]
That would rock!! Yes yes, please! 

To be clear, it's just the function definitions themselves. I'll let @Simek explain more :)

**Comment by luism3861** [comment]
> That would rock!! Yes yes, please!
> 
> To be clear, it's just the function definitions themselves. I'll let @Simek explain more :)

thanks :) !!!

**Comment by luism3861** [comment]
@Simek  could you lend me explain about how to convert  examples with functions?

**Comment by Simek** [comment]
@luism3861 At the beginning I want to thank you for all the contributions you have made lately, good stuff!

According to the arrow functions situation: We are working on the bigger code standardization issue (something like Component Docs Drive) so the whole community got the opportunity to contribute. Please look for it in the next few days!

**Comment by luism3861** [comment]
> @luism3861 At the beginning I want to thank you for all the contributions you have made lately!
> 
> According to the arrow functions situation: We are working on the bigger code standardization issue (something like Component Docs Drive) so the whole community got the opportunity to contribute. Please look for it in the next few days!

thank you @Simek  i will check issues for this new opportunity to contribute :D !!

**Pull request closed without merging**
