### PR TITLE
file: Update Facebook logo

### LINKED ISSUE #1524: Update Facebook Logo
## Overview 

The Facebook logo on the showcase page should be updated to the new logo.

## Screen

Screen Shot 2019-12-26 at 11 01 55 AM

### PR DESCRIPTION
**Pull request by elharony**
This PR fixes #1524 

## What's new?
Replace the old Facebook logo with the new, optimized logo (200x200) similar to #1361 

| Old | New |
| ------------- | ------------- |
|  | facebook |

### CODE REVIEW

**Comment by rickhanlonii** [comment]
This is great! Can you resolve the merge conflict?

**Comment by elharony** [comment]
Thanks @rickhanlonii . I cannot resolve the conflict (the option is disabled). The conflicting files are only the Facebook logo that I’ve updated.

Can you please tell me how can I fix it? Thanks!

**Comment by rickhanlonii** [comment]
@elharony it looks like you branched off of master before your other change landed which means facebook.png is different on both master and on this PR, so git doesn't know how to resolve the conflict.

In order to resolve manually you'll need to checkout your branch locally.

If you give me access to edit the PR then I can push up a fix for you!

**Comment by elharony** [comment]
Hey @rickhanlonii, I tried to do it myself, but it seems that I did a huge mess! 😄

**Comment by rickhanlonii** [comment]
Oh yeah, that happens! To fix, I would rebuild the branch from master with the change you want and then force push to this branch.

I have it fixed locally but I’m not allowed to push to your repo, if you give me access I can help out 👍

**Comment by elharony** [comment]
Thank you, @rickhanlonii 🙋🏻‍♂️
Just added you as a collaborator on my repo so you can push 🤞🏻

**Comment by rickhanlonii** [comment]
Hm I still can't push to it :c

**Comment by rickhanlonii** [comment]
If you want, you could re-pull master, add the changes, and submit a new PR

**Comment by elharony** [comment]
Good idea, @rickhanlonii . Done! 👍

**Pull request closed without merging**
