### PR TITLE
Update threading-model.md typo

### PR DESCRIPTION
**Pull request by beesnat-chr**
Fixed an assumed typo.

### CODE REVIEW

**Review by cortinico — APPROVED** [review]

**Comment by cortinico** [comment]
Hi @beesnat-chr,
Can I ask you to sign the CLA otherwise we can't merge this PR

**Comment by beesnat-chr** [comment]
Done!
________________________________

**Comment by cortinico** [comment]
> Done!

The bot hasn't recognized this yet. It can take some time.
In the meanwhile, could you resolve the conflict on the file?

**Comment by Simek** [comment]
Hello @beesnat-chr, can you rebase your PR and resolve the conflict? 

The reason why there is conflict is that the doc file has been moved from the unversioned docs, to the static ones, and now it's located in `website/architecture` directory.

**Comment by Simek** [comment]
Closing in favor of #3089.

**Pull request closed without merging**
