### PR TITLE
fix: Cocoapods -> CocoaPods

### PR DESCRIPTION
**Pull request by blakef**
Also added it to antfu/case-police#148 so our tooling will fix this in the future.

### CODE REVIEW

**Review by Simek — APPROVED** [review]
LGTM. Nice idea to propose that upstream. 👍 

Btw., we can also define the custom dict which can extend the included in `case-police` checks. We do this in Expo repo currently:
* https://github.com/expo/expo/blob/main/docs/expo-dict.json

**Comment by blakef** [comment]
> LGTM. Nice idea to propose that upstream. 👍
> 
> Btw., we can also define the custom dict for more niche terms which can extend the included in `case-police` checks. We do this in Expo repo currently:
> 
> * https://github.com/expo/expo/blob/main/docs/expo-dict.json

That's a great callout, so I'll add it here.  I'd anticipate this isn't the last time we'll hit something similar.

**Comment by Simek** [comment]
You also need to pass the dict path via param in the command:
* https://github.com/expo/expo/blob/main/docs/package.json#L15

It is also good to verify that case-police works as expected, IIRC the order of prams matters, for example, for rules overwrites.

**Review by cortinico — APPROVED** [review]

**Comment by blakef** [comment]
> You also need to pass the dict path via param in the command:
> 
> * https://github.com/expo/expo/blob/main/docs/package.json#L15
> 
> It is also good to verify that case-police works as expected, IIRC the order of prams matters, for example, for rules overwrites.

Thanks for pointing this out @Simek , I was in too much of a hurry and didn't commit my `package.json` changes.  I've thrown those up here: #3597.

**Pull request merged**
