### PR TITLE
Add documentation for Hermes sampling profiler

### PR DESCRIPTION
**Pull request by jessieAnhNguyen**
## Summary:
---------

This PR adds a new doc for Hermes sampling profiler. This is built as part of the goal to visualize the performance of JavaScript running on Hermes in a React Native app. @saphal1998 and I worked on this under @axemclion and @jevakallio guidance.

- This new documentation `profile-hermes.md` instructs the user on:
    - How to profile their React Native app running on Hermes. 
    - How to use the command to download Hermes profile (this feature will land soon once this PR https://github.com/react-native-community/cli/pull/1246 is approved)
    - How to visualize the profile using Chrome DevTools
    - Understanding how the [Hermes Profile Transformer](https://github.com/react-native-community/hermes-profile-transformer) works

- The doc is added to the sidebar in the `Performance` session, right after `Profiling`

## Test Plan:
----------
- We followed the instruction on [Making a change](https://github.com/facebook/react-native-website#make-the-change)
- The new doc looks like this
image

### CODE REVIEW

**Comment by Simek** [comment]
Hi @jessieAnhNguyen, thank you so much this article, it is a great addition! 👍 

Unfortunately there are some minor display issues on the newly added page (due to Markdown parsing by Docususaurus):
Annotation 2020-08-20 103615

Let me know if you will have any problems, I can try to help, preview:
https://deploy-preview-2159--react-native.netlify.app/docs/next/profile-hermes

**Comment by saphal1998** [comment]
@Simek, thank you so much for getting back to us so soon. We have resolved the markdown parsing issue, the PR should be ready for review! :tada:

**Comment by Simek** [comment]
@saphal1998 After the tweaks, from the technical stand point this PR LGTM, but since it is a bigger addition I have asked @rachelnabors to review the content 🙂

**Review by rachelnabors — CHANGES_REQUESTED** [review]
I made a PR of a few changes—great stuff! I would like to go through one more time, but first, please check that the step-by-step instructions conform to our [menu/command styleguides](https://github.com/facebook/react-native-website/blob/master/STYLEGUIDE.md#format-menu-paths). Thank you!

**Comment by rachelnabors** [comment]
Hey there, I PRed some changes to this PR. Could you merge them so we can merge this? Thanks!

**Comment by saphal1998** [comment]
Thanks for the review! We have merged the changes @rachelnabors

**Review by rachelnabors — CHANGES_REQUESTED** [review]
Looks good. One last thing: Remove the first image under "enable sampling profiler"—it doesn't really explain anything.

**Comment by davelyon** [comment]
Thanks so much for documenting this, it's been immensely helpful for me! I wanted to share some feedback around the "Open the downloaded profile in Chrome DevTools" step. I haven't been able to get the regular devtools to correctly open the file, but I have been consistently able to get them open and viewable by using the tracing view at `chrome://tracing` and loading there.

I may have misunderstood how to get to the right state with the Chrome DevTools, so it might be that some clarification is needed on that step, otherwise I would suggest that the documentation direct users to the `chrome://tracing` page.

Thanks again for documenting this! :+1:

**Comment by jessieAnhNguyen** [comment]
Hi @rachelnabors, I've deleted the image. Thanks for reviewing!

**Comment by saphal1998** [comment]
Hi @davelyon, so `chrome://tracing` opens the profile even without transforming it (i.e. the raw `.cpuprofile` file), however in that case, we cannot interpret much from the visualisation. This is why we opted for the visualisation in the `Performance` tab. So, can you, if possible, post the image of your performance profile on `chrome://tracing` and Chrome DevTools so that we can compare the two? Or even validate if they look identical?

I just want to check if the transformation took place. If the transformation did take place, then the visualisation on both of these should be identical according to us.

**Comment by rachelnabors** [comment]
Hey hey! Since @davelyon hasn't responded, I'm going to merge your PR. (If future edits are necessary, you can always edit the doc or file an issue!)

Thank you for your patience and hard work on this! Your contribution has made the docs more useful to more people :)

2020_me_thanks

**Pull request merged**
