### PR TITLE
Add table of contents and encourage people to leave feedback in working group in Architecture Overview intro

### PR DESCRIPTION
**Pull request by sammy-SC**
screencapture-localhost-3000-docs-architecture-overview-2022-03-08-13_09_16

### CODE REVIEW

**Review by cortinico — APPROVED** [review]

**Comment by cortinico** [comment]
Marked as ready for review @sammy-SC. I'm happy to merge this or take this over as you prefer

**Comment by Simek** [comment]
FYI: We have unversioned the New Architecture docs just a moment ago, the files can now be found under `website/architecture` path.

**Comment by Simek** [comment]
Also, personally, I'm not a big fan of in content ToC, since we have features like sidebar and docs ToC on the right. 

At this moment is look like this ToC mimic the content of the sidebar, which do not add that much. Additionally, maintaining manual links like those might be a bit cumbersome in a long term, because we need to remember to pay attention and update the section on each slug change, page added or architecture sidebar structure changes.

**Comment by cortinico** [comment]
> At this moment is look like this ToC mimic the content of the sidebar, which do not add that much

I'm in for merging this right now, as we don't have much content in the landing page of this new Arch. section. We will add more in the coming weeks/months. Right now it feels a bit empty.

The problem is also that if you're on mobile, you'll end up on a half-empty page and is unclear where to go next. That's why I suggested to add links to the Fabric section (in the form of a TOC or any other form).

**Comment by sammy-SC** [comment]
@Simek This PR was meant to address some of that emptiness. It still could use more work.

I agree with all the arguments you and @cortinico have made. I'll resolve the conflicts and merge this as I feel like this is still an improvement. We can keep iterating on the intro.

Thank you.

**Pull request merged**
