### PR TITLE
Revert React Conf 2024 banner

### PR DESCRIPTION
**Pull request by Abbondanzo**
React Conf has sadly ended. Time to revert #4066

### CODE REVIEW

**Comment by cortinico** [comment]
True, but I'd keep in sync with react.dev (which haven't removed the banner just yet)

**Comment by Abbondanzo** [comment]
> True, but I'd keep in sync with react.dev (which haven't removed the banner just yet)

Added a PR to revert the banner on react.dev too: https://github.com/reactjs/react.dev/pull/6891

**Comment by Abbondanzo** [comment]
@cortinico react.dev has removed their banner altogether. I can modify this PR to do the same but it'd be nice to keep the old banner if possible

**Comment by cortinico** [comment]
> react.dev has removed their banner altogether. I can modify this PR to do the same but it'd be nice to keep the old banner if possible

I'd rather keep the two website in sync so let's just remove the banner and follow react.dev

**Review by cortinico — APPROVED** [review]

**Pull request merged**
