### PR TITLE
Missing instruction to compile kotlin and a variable type in CenteredTextManager.kt causing build failure and wrong variable type. #3681

### PR DESCRIPTION
**Pull request by ddepu11**
There are no instruction for compiling kotlin files in `RTNCenteredText/android/build.gradle`. After adding those instruction in gradle it compiles the kotlin files.

But now we get error in the file `CenteredTextManager.kt` at line no 14 where the variable `delegate` has type `RTNCenteredTextManagerDelegate<CenteredText>` and this `RTNCenteredTextManagerDelegate` asks for second type.

So i just replaced it with ViewManagerDelegate<CenteredText> and it worked. I have replace RTNCenteredTextManagerDelegate with ViewManagerDelegate in docs.

```
private val delegate: ViewManagerDelegate<CenteredText> = RTNCenteredTextManagerDelegate(this)

```

### CODE REVIEW

**Comment by dm20** [comment]
Hi all, I had the same issue and I tried this and it seemed to allow compilation to work, so thanks very much for that. But when I load the centered text component in my RN app, I see no text or component. It is just an empty view. Can we verify that this change does not break something else causing an issue like an empty view to be rendered?

**Comment by dm20** [comment]
I am using Kotlin, is my issue maybe because I need to make the build.gradle change as well so that my Kotlin files get compiled?

**Comment by dm20** [comment]
Ah wait, I see the comment about tabbed approach. I followed that and used the build.gradle that is currently on the website so i think I am good. 

So still question remains, does this change break something that causes an empty View to get rendered?

**Comment by cortinico** [comment]
Closing as this has already been fixed

**Pull request closed without merging**
