### PR TITLE
rename type and method from GreetingsProps to GreetingProps

### PR DESCRIPTION
**Pull request by ahmadaliyu**

### CODE REVIEW

**Comment by Simek** [comment]
Hello @ahmadaliyu, what's the reason for the type rename?

**Comment by ahmadaliyu** [comment]
According to the issue number #3519 opened by NickGerleman Renaming
GreetingsProps to GreetingProp. Named it "GreetingsProps" for "Greeting"
(non-plural) which should be fix

**Review by cortinico — APPROVED** [review]

**Comment by NickGerleman** [comment]
Thanks for the change!

**Comment by ahmadaliyu** [comment]
You are welcome, happy to help

**Pull request merged**
