### PR TITLE
Update tsconfig.json example

### PR DESCRIPTION
**Pull request by retyui**
React Native `0.63` requires iOS `10.x`, and bundles a modern version of JSC on Android, we can update the JavaScript library version to `es2017`. That brings in declarations for:

- `Array.prototype.includes`
- `Object.entries` and `Object.values`
- `String.padStart` and `String.padEnd`

Other links:
- [`@tsconfig/react-native`](https://github.com/tsconfig/bases/blob/d392e64aa0efc3ac6e2840c358a9de919481165b/bases/react-native.json#L8)
- [`react-native-community/react-native-template-typescript/tsconfig.json`](https://github.com/react-native-community/react-native-template-typescript/blob/b3300f9c7fc383504b1a0b3abaffc801eea830e8/template/tsconfig.json#L7)

### CODE REVIEW

**Comment by retyui** [comment]
Preview
- https://deploy-preview-2796--react-native.netlify.app/docs/0.63/typescript
- https://deploy-preview-2796--react-native.netlify.app/docs/0.64/typescript
- https://deploy-preview-2796--react-native.netlify.app/docs/typescript
- https://deploy-preview-2796--react-native.netlify.app/docs/next/typescript

**Review by Simek — CHANGES_REQUESTED** [review]
Hi @retyui, thank you for the update and the links with the context for the change! 👍 

Since you have updated the versioned docs, can you also rebase your PR and update the `0.66` docs file, so the file will be the same for 0.63 version and onwards?

**Comment by retyui** [comment]
@simek done

**Review by Simek — APPROVED** [review]
Thank you for the review updates! 🙂

**Pull request merged**
