### PR TITLE
Update use-app-template.md

### PR DESCRIPTION
**Pull request by Gregoirevda**
ruby function `install_modules_dependencies` was added in 0.71.0-rc.3 https://github.com/facebook/react-native/commit/82e9c6ad611f1fb816de056ff031716f8cb24b4e

### CODE REVIEW

**Comment by Gregoirevda** [comment]
@cortinico The [podspec](https://reactnative.dev/docs/next/the-new-architecture/pillars-fabric-components#ios-create-the-podspec-file) file uses the ruby function `install_modules_dependencies` which isn't available in latest react-native version (the function was only added in the commit I've referenced which is available under the npmjs next tag)

**Comment by cortinico** [comment]
> We should generally avoid adding version numbers in documents like this since they age poorly. E.g. the document will stay the same once 0.72 comes out.

True. Yet for the New Architecture setup, the version number is sort of crucial IMHO as we're keep on iterating on the migration path.

**Comment by cipolleschi** [comment]
Hi @Gregoirevda, thank you a lot for the PR. However, I don't think we have to merge this.

The `podspec` file you mention is in the Fabric Components. The Fabric Component page has this lines:
> The following section guides you through the creation of a Fabric Native Component, step-by-step, targeting the latest version of React Native
By the time we ship this documentation page, 0.71 will be the latest version of React Native, so the documentation is correct.

You are suggesting to change the `[use-app-template.md](https://github.com/facebook/react-native-website/pull/3455/files#diff-ab38314fcc7012e596ef41d1c26754017d05a18803f41a684fc4f5a7f50a1db8)` page which is a page where we are helping people to get started with their apps
1. Apps have nothing to spare with the `podspecs`, which are for libraries. It would be confusing for the user to look at the documentation and see a specific version of React Native (especially an RC) just to discover that it is due to the lib configurations. 
2. By the time we release the change, 0.71 would be the lastest stable and your changes will be outdated, requiring another update.

What do you think?

**Review by cipolleschi — CHANGES_REQUESTED** [review]
See comment above

**Comment by Gregoirevda** [comment]
Makes sense to not include version numbers, especially RC. Just a matter of time before `install_modules_dependencies` is included in `latest`

**Pull request closed without merging**
