### PR TITLE
Edit useCallback hook

### PR DESCRIPTION
**Pull request by mojvan**
Hello..
I think an updated parameter is needed for useCallback hook otherwise we don't need this hook....
Good luck...

### CODE REVIEW

**Review by mojvan — COMMENTED** [review]
@Simec , I'm waiting for your answer

**Comment by Simek** [comment]
Refs #1845

Hi @mojvan, thank you for proposing those changes, but in this specific case `useMemo` would be enough and generally you need to remember it's just an example. Using `useCallback` here is more coherent with the general usage pattern in "real" use cases (when some async operations will be executed). Also change to the `setRefreshing` value in the changeset cause an incorrect behavior.

**Comment by mojvan** [comment]
@Simek , do you can show me this incorrect behavior?
Thank you

**Review by mojvan — COMMENTED** [review]
@Simek , can you show me the incorrect behavior?
Thank you

**Pull request closed without merging**
