### PR TITLE
Update docs for https://github.com/facebook/react-native/pull/17747

### PR DESCRIPTION
**Pull request by msand**
Update docs for https://github.com/facebook/react-native/pull/17747

### CODE REVIEW

**Comment by hramos** [comment]
Thanks, let's come back to this when the PR is merged.

**Comment by hey99xx** [comment]
Wait how does this commit makes sense without updating build.gradle of react-native simultaneously? 

This is changing

> Android SDK version ~~23~~ 27 (compileSdkVersion in [`build.gradle`](https://github.com/facebook/react-native/blob/master/ReactAndroid/build.gradle))

and 

> SDK build tools version ~23.0.1~~ 26.0.2 (buildToolsVersion in [`build.gradle`](https://github.com/facebook/react-native/blob/master/ReactAndroid/build.gradle))

But if you look at the [relevant part of build.gradle](https://github.com/facebook/react-native/blob/0.54-stable/ReactAndroid/build.gradle#L234) the numbers there are still are

```
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"
```

So I think merging this PR as it is will only create confusion, because the docs will suggest Android tools that have a mismatch with what RN actually uses.

**Comment by msand** [comment]
@hey99xx I had updated and force-push to the branch in the PR in RN, and am waiting for more feedback https://github.com/facebook/react-native/pull/17747#issuecomment-363969697 
Haven't updated this PR to reflect the changes in versions there yet.

**Comment by msand** [comment]
But, the instructions about build tool versions could probably be removed completely, as the new gradle version will pick one itself depending on compatibility.

**Comment by cpojer** [comment]
It seems like this is outdated now and we'll need a new PR with the latest versions for everything. Sorry that it took so long to get back to this.

**Pull request closed without merging**
