### PR TITLE
add missing `npm install` to getting started doc

### PR DESCRIPTION
**Pull request by nylki**

### CODE REVIEW

**Comment by charpeni** [comment]
What's your motivation?

You shouldn't have to run `npm install`, dependencies are installed by `create-react-native-app`.

**Comment by nylki** [comment]
Hi, @charpeni 
I tried to run the setup again so I can give you better feedback:

When running `create-react-native-app` I get an error, seen below. Ignoring that and continuing to `cd AwsomeProject` and `npm start` it says: `Error: React native is not installed. Please run `npm install` in your project directory.`
Doing `npm install`, as advised and then running `npm start` works fine though, giving me the QR-code and everything.

I suppose the actual issue here is the error, occuring in `create-react-native-app`.
I am using npm v6.1.0, node v10.4.0, create-react-native-app v1.0.0 on Fedora 28.





```.sh
➜  react-native-experiments create-react-native-app AwesomeProject
Creating a new React Native app in /home/tom/Programming/react-native-experiments/AwesomeProject.

Using package manager as npm with npm interface.
Installing packages. This might take a couple minutes.
Installing react-native-scripts...

npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-darwin-x64@2.2.8 (node_modules/@expo/ngrok-bin-darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-darwin-x64@2.2.8: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-freebsd-ia32@2.2.8 (node_modules/@expo/ngrok-bin-freebsd-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-freebsd-ia32@2.2.8: wanted {"os":"freebsd","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-darwin-ia32@2.2.8 (node_modules/@expo/ngrok-bin-darwin-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-darwin-ia32@2.2.8: wanted {"os":"darwin","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-freebsd-x64@2.2.8 (node_modules/@expo/ngrok-bin-freebsd-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-freebsd-x64@2.2.8: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-linux-arm@2.2.8 (node_modules/@expo/ngrok-bin-linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-linux-arm@2.2.8: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-linux-arm64@2.2.8 (node_modules/@expo/ngrok-bin-linux-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-linux-arm64@2.2.8: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-linux-ia32@2.2.8 (node_modules/@expo/ngrok-bin-linux-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-linux-ia32@2.2.8: wanted {"os":"linux","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-sunos-x64@2.2.8 (node_modules/@expo/ngrok-bin-sunos-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-sunos-x64@2.2.8: wanted {"os":"sunos","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-win32-ia32@2.2.8-beta.1 (node_modules/@expo/ngrok-bin-win32-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-win32-ia32@2.2.8-beta.1: wanted {"os":"win32","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/ngrok-bin-win32-x64@2.2.8-beta.1 (node_modules/@expo/ngrok-bin-win32-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/ngrok-bin-win32-x64@2.2.8-beta.1: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})

+ react-native-scripts@1.14.0
added 442 packages from 477 contributors and audited 1178 packages in 27.988s
found 2 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
Installing dependencies using yarn...

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarnpkg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
➜  react-native-experiments cd AwesomeProject 
➜  AwesomeProject npm start

> AwesomeProject@0.1.0 start /home/tom/Programming/react-native-experiments/AwesomeProject
> react-native-scripts start

10:45:37: Starting packager...
***ERROR STARTING PACKAGER***

Error: React native is not installed. Please run `npm install` in your project directory.
10:45:40: Error starting packager: Error: Couldn't start project. Please fix the errors and restart the project.
    at /xdl/src/Project.js:1329:11
    at Generator.next (<anonymous>)
    at step (/home/tom/Programming/react-native-experiments/AwesomeProject/node_modules/xdl/build/Project.js:1735:191)
    at /home/tom/Programming/react-native-experiments/AwesomeProject/node_modules/xdl/build/Project.js:1735:361
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! AwesomeProject@0.1.0 start: `react-native-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the AwesomeProject@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tom/.npm/_logs/2018-06-27T08_45_40_571Z-debug.log
➜  AwesomeProject 
```

**Comment by nylki** [comment]
Here is the output of npm's debug log:
```.sh
cat /home/tom/.npm/_logs/2018-06-27T08_45_40_571Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/home/tom/.nvm/versions/node/v10.4.0/bin/node',
1 verbose cli   '/home/tom/.nvm/versions/node/v10.4.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.1.0
3 info using node@v10.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle AwesomeProject@0.1.0~prestart: AwesomeProject@0.1.0
6 info lifecycle AwesomeProject@0.1.0~start: AwesomeProject@0.1.0
7 verbose lifecycle AwesomeProject@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle AwesomeProject@0.1.0~start: PATH: /home/tom/.nvm/versions/node/v10.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/tom/Programming/react-native-experiments/AwesomeProject/node_modules/.bin:/home/tom/bin/zotero:/home/tom/torch/install/bin:/home/tom/bin:/usr/local/bin:/home/tom/.nvm/versions/node/v10.4.0/bin:/home/tom/bin:/home/tom/.local/bin:/home/tom/node_modules/bin:/usr/lib64/qt-3.3/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/tom/bin:/home/tom/AndroidSDK:/home/tom/AndroidSDK/tools:/home/tom/AndroidSDK/platform-tools:/home/tom/dotnet:/home/tom/.cargo/bin
9 verbose lifecycle AwesomeProject@0.1.0~start: CWD: /home/tom/Programming/react-native-experiments/AwesomeProject
10 silly lifecycle AwesomeProject@0.1.0~start: Args: [ '-c', 'react-native-scripts start' ]
11 silly lifecycle AwesomeProject@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle AwesomeProject@0.1.0~start: Failed to exec start script
13 verbose stack Error: AwesomeProject@0.1.0 start: `react-native-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/tom/.nvm/versions/node/v10.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/tom/.nvm/versions/node/v10.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid AwesomeProject@0.1.0
15 verbose cwd /home/tom/Programming/react-native-experiments/AwesomeProject
16 verbose Linux 4.17.2-200.fc28.x86_64
17 verbose argv "/home/tom/.nvm/versions/node/v10.4.0/bin/node" "/home/tom/.nvm/versions/node/v10.4.0/bin/npm" "start"
18 verbose node v10.4.0
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error AwesomeProject@0.1.0 start: `react-native-scripts start`
22 error Exit status 1
23 error Failed at the AwesomeProject@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by nylki** [comment]
Here is the output of `npm audit` in the created project:
```.sh
➜  AwesomeProject npm audit
npm ERR! code ELOCKVERIFY
npm ERR! Errors were found in your package-lock.json, run  npm install  to fix them.
npm ERR!     Missing: expo@^27.0.1
npm ERR!     Invalid: lock file's react@16.4.1 does not satisfy react@16.3.1
npm ERR!     Missing: react-native@~0.55.2
npm ERR!     Missing: jest-expo@~27.0.0
npm ERR!     Missing: react-test-renderer@16.3.1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tom/.npm/_logs/2018-06-27T08_56_51_421Z-debug.log
```

Should I create an issue in https://github.com/react-community/create-react-native-app ?

**Comment by charpeni** [comment]
> Should I create an issue in https://github.com/react-community/create-react-native-app ?

Yes, it doesn't look related to react native itself. Let's close it here.

**Pull request closed without merging**
