### PR TITLE
Adding Social Banner in Support of Ukraine 

### PR DESCRIPTION
**Pull request by dmitryvinn**
## Summary
Our mission at [Meta Open Source](https://opensource.facebook.com/) is to empower communities through open source, and we believe that it means building a welcoming and safe environment for all. As a part of this work, we are adding this banner in support for Ukraine during this crisis.

## Testing
image

### CODE REVIEW

**Comment by dmitryvinn-fb** [comment]
Note: following this PR, we will be closing https://github.com/facebook/react-native/pull/33192

**Review by Simek — COMMENTED** [review]
Can we use announcement banner feature for this, instead of implementing custom component?
* https://docusaurus.io/docs/next/api/themes/configuration#announcement-bar

We have used this feature before in few occasions and it should looks something like that:

**Comment by yungsters** [comment]
In the spirit of getting this published as soon as possible, I'm merging this. But let's fix forward if we believe this can be done better.

**Comment by leggomuhgreggo** [comment]
Curious about the decision making process here. This one is -- let's just say [controversial](https://twitter.com/consent_factory/status/1498257865693405185).

**Pull request merged**
