### PR TITLE
fix bug in documentation

### PR DESCRIPTION
**Pull request by ffMathy**

### CODE REVIEW

**Comment by rachelnabors** [comment]
Duplicate of #1452 Thank you for your vigilance!

**Comment by rachelnabors** [comment]
Accidentally closed

**Comment by ffMathy** [comment]
Wow, is this PR still open? 😲

**Comment by orta** [comment]
I tested the new  command and it doesn't look like it works to me:

Screen Shot 2019-11-25 at 10 20 04 AM

Perhaps something changed?

**Comment by ffMathy** [comment]
Try from Windows.

**Comment by orta** [comment]
Can you please show that this works rather than asking me to go find another computer to test it on. 

it's trying to access a file in the module `typescript` which isn't a template for react native's CLI

**Comment by orta** [comment]
In #1419 there's a mention about having a global installed somehow, I'm not sure what's up but IMO this is a bug in the CLI

**Comment by rachelnabors** [comment]
I defer to Orta, but also—if this is a bug in the CLI, perhaps the PR we need explains the bug and provides a workaround? I would totally approve _that!_

**Pull request closed without merging**
