### PR TITLE
Adopt OpenJDK11

### PR DESCRIPTION
**Pull request by svbutko**
Based on Gradle version upgrade it will be needed to install JDK 11:
https://github.com/facebook/react-native/pull/32186

### CODE REVIEW

**Comment by cortinico** [comment]
@svbutko Can I ask you to rebase as this I believe is ready to land 👍

**Comment by Simek** [comment]
The change has landed only on `main`, so we need to wait for the 0.67 cut to happen, to merge this PR in.

**Comment by cortinico** [comment]
> The change has landed only on `main`, so we need to wait for the 0.67 cut to happen, to merge this PR in.

This change is backward compatible though. You can use JDK 11 to build previous version of RN without problems. With the upcoming version instead, it will become a requirement.

**Comment by kelset** [comment]
@Simek I think you meant to say 0.68?

**Comment by Simek** [comment]
Not exactly, I should write that we need to wait for the 0.67 docs cut merge, not only the cut. :)

If we merge this now, for a while, the change will appear in `next` docs, which will be incorrect, but after the merge of `0.67` cut the `next` version will represent the state of `0.68`.

**Comment by kelset** [comment]
gotcha: so version 0.67 of react-native is not affected by this, so this PR can only be merged *after* this PR is merged: https://github.com/facebook/react-native-website/pull/2926

correct?

**Comment by cortinico** [comment]
> If we merge this now, for a while, the change will appear in `next` docs, which will be incorrect, but after the merge of `0.67` cut the `next` version will represent the state of `0.68`.

Just to clarify: this specific change is making JDK 11 the "suggested" JDK versions.
It necessarily needs to be in the 0.68 docs, as there it will be come a hard requirement. It won't hurt to have it inside the 0.67 docs as well as JDK versions are backwards compatibles.

**Comment by Simek** [comment]
@cortinico Thanks for the clarification! So we can merge it now, right?

**Comment by cortinico** [comment]
> So we can merge it now, right?

Essentially yes 👍

**Review by Simek — APPROVED** [review]

**Comment by Simek** [comment]
To see this change in the `0.67` docs we need to cherry pick this commit into `0.67` docs cut or just sync the cut branch with `main`. CC @kelset

**Comment by kelset** [comment]
ok, let me rebase my branch on top of main for good measure and re-gen the docs

**Comment by kelset** [comment]
(done: https://github.com/facebook/react-native-website/pull/2926#issuecomment-1016438172 )

**Pull request merged**
