### PR TITLE
Documentation about proposed RCTSetCustomNSURLSessionConfigurationProvider

### PR DESCRIPTION
**Pull request by hakonk**
This PR contains documentation for the proposed changes in this PR https://github.com/facebook/react-native/pull/27701.

### CODE REVIEW

**Review by Simek — CHANGES_REQUESTED** [review]
Hi @hakonk, thank you for the companion PR for the docs! 👍 

However you have edited the docs for `0.64` release, when the changes should be part of `next` version:
* https://github.com/facebook/react-native-website/blob/master/docs/network.md

Please move the new section to the suggested file above and then PR should be ready to be merged after the `0.65` release. 🙂

**Comment by hakonk** [comment]
Hi @Simek ! I have moved the comment now 🙂

**Review by Simek — APPROVED** [review]
@hakonk Thank you for the update! 👍

**Comment by taylorkline** [comment]
@hakonk If you don't mind, after applying the patch with `patch-package` from facebook/react-native@c299694c87e9912d4c884b5acec04c708ed0f841:

```patch
diff --git a/node_modules/react-native/Libraries/Network/RCTHTTPRequestHandler.h b/node_modules/react-native/Libraries/Network/RCTHTTPRequestHandler.h
index 75b84eb..5a91bd0 100644
--- a/node_modules/react-native/Libraries/Network/RCTHTTPRequestHandler.h
+++ b/node_modules/react-native/Libraries/Network/RCTHTTPRequestHandler.h
@@ -8,6 +8,11 @@
 #import <React/RCTInvalidating.h>
 #import <React/RCTURLRequestHandler.h>
 
+typedef NSURLSessionConfiguration* (^NSURLSessionConfigurationProvider)(void);
+/**
+ *  The block provided via this function will provide the NSURLSessionConfiguration for all HTTP requests made by the app.
+*/
+RCT_EXTERN void RCTSetCustomNSURLSessionConfigurationProvider(NSURLSessionConfigurationProvider);
 /**
  * This is the default RCTURLRequestHandler implementation for HTTP requests.
  */
diff --git a/node_modules/react-native/Libraries/Network/RCTHTTPRequestHandler.mm b/node_modules/react-native/Libraries/Network/RCTHTTPRequestHandler.mm
index 274f381..b500f5a 100644
--- a/node_modules/react-native/Libraries/Network/RCTHTTPRequestHandler.mm
+++ b/node_modules/react-native/Libraries/Network/RCTHTTPRequestHandler.mm
@@ -18,6 +18,12 @@
 
 @end
 
+static NSURLSessionConfigurationProvider urlSessionConfigurationProvider;
+
+void RCTSetCustomNSURLSessionConfigurationProvider(NSURLSessionConfigurationProvider provider) {
+  urlSessionConfigurationProvider = provider;
+}
+
 @implementation RCTHTTPRequestHandler
 {
   NSMapTable *_delegates;
@@ -75,14 +81,20 @@ RCT_EXPORT_MODULE()
     NSOperationQueue *callbackQueue = [NSOperationQueue new];
     callbackQueue.maxConcurrentOperationCount = 1;
     callbackQueue.underlyingQueue = [[_bridge networking] methodQueue];
-    NSURLSessionConfiguration *configuration = [NSURLSessionConfiguration defaultSessionConfiguration];
-    // Set allowsCellularAccess to NO ONLY if key ReactNetworkForceWifiOnly exists AND its value is YES
-    if (useWifiOnly) {
-      configuration.allowsCellularAccess = ![useWifiOnly boolValue];
+    NSURLSessionConfiguration *configuration;
+    if (urlSessionConfigurationProvider) {
+      configuration = urlSessionConfigurationProvider();
+    } else {
+      configuration = [NSURLSessionConfiguration defaultSessionConfiguration];
+      // Set allowsCellularAccess to NO ONLY if key ReactNetworkForceWifiOnly exists AND its value is YES
+      if (useWifiOnly) {
+        configuration.allowsCellularAccess = ![useWifiOnly boolValue];
+      }
+      [configuration setHTTPShouldSetCookies:YES];
+      [configuration setHTTPCookieAcceptPolicy:NSHTTPCookieAcceptPolicyAlways];
+      [configuration setHTTPCookieStorage:[NSHTTPCookieStorage sharedHTTPCookieStorage]];
     }
-    [configuration setHTTPShouldSetCookies:YES];
-    [configuration setHTTPCookieAcceptPolicy:NSHTTPCookieAcceptPolicyAlways];
-    [configuration setHTTPCookieStorage:[NSHTTPCookieStorage sharedHTTPCookieStorage]];
+    assert(configuration != nil);
     _session = [NSURLSession sessionWithConfiguration:configuration
                                              delegate:self
                                         delegateQueue:callbackQueue];
```

Should I be able to use the example in this PR after a simple `yarn install` and `pod install`?

As of right now, adding `#import <React/RCTSetCustomNSURLSessionConfigurationProvider.h>` results in `'React/RCTSetCustomNSURLSessionConfigurationProvider.h' file not found`

**Comment by hakonk** [comment]
Hi, @taylorkline! I believe the correct import should be `#import <React/RCTHTTPRequestHandler.h>`, as `RCTSetCustomNSURLSessionConfigurationProvider` is exposed via that file. That's probably worthy a comment though.

**Review by Simek — APPROVED** [review]

**Comment by hakonk** [comment]
I'm confused. As pointed out [here](https://github.com/facebook/react-native/pull/27701#issuecomment-900823660), the PR that this documentation describes the usage of will apparently not be included in 0.65. It will however be included in 0.66. @Simek

**Comment by Simek** [comment]
@hakonk the `0.65` release has been published yester and docs for `0.65` has been cut and deployed.
After that the `next` docs became the future `0.66` release docs, so all the PRs with upcoming changes, which already landed in core repository can be merged in. 🙂 

Currently the problem is that your PR updates the base file, not the `next` docs, which need to be corrected. I did not spotted this during the merge.

**Comment by hakonk** [comment]
@Simek I found out it was included after all, please see this [comment](https://github.com/facebook/react-native/pull/27701#issuecomment-900892072). Sorry for the confusion.

**Comment by Simek** [comment]
> @Simek I found out it was included after all, please see this [comment](https://github.com/facebook/react-native/pull/27701#issuecomment-900892072). Sorry for the confusion.

Oh, that make sense, so we need to backport this PR to `0.65`, would you like to do this?

**Comment by hakonk** [comment]
I willing to contribute, however, I'm unsure what kind of branching strategy you find appropriate to achieve this.

**Comment by Simek** [comment]
All the "versioned" docs are located under `website/versioned_docs` directory and can be edited freely. You can read a bit more in the Readme: 
* https://github.com/facebook/react-native-website#versioned-docs

This is how the Docusaurus works, we do not use separate branches for the docs releases to keep it simple and to allow an easy editing or backporting in the older docs. 🙂

**Pull request merged**
