### PR TITLE
Update Link to gradle.properties in Image Documentation

### PR DESCRIPTION
**Pull request by ridsameer**

### CODE REVIEW

**Review by Simek — COMMENTED** [review]
Hello @ridsameer, thank you for the link update! 👍 

Can you also backport this change to at least few last versioned docs? Versioned files are located here:
* https://github.com/facebook/react-native-website/tree/main/website/versioned_docs

**Review by cortinico — APPROVED** [review]

**Comment by cortinico** [comment]
> Can you also backport this change to at least few last versioned docs? Versioned files are located here:

Actually that's unnecessary IMHO. Specifically as previous "tagged version" as mentione in the doc will have the file in the original location

**Comment by cortinico** [comment]
@ridsameer can I ask you to sign the CLA?

**Comment by Simek** [comment]
> Actually that's unnecessary IMHO. Specifically as previous "tagged version" as mentione in the doc will have the file in the original location

All links in previous version of documentation lead to the `main` branch, so maybe we should change them to point to the release branches instead?
* https://github.com/search?q=repo%3Afacebook%2Freact-native-website%20ReactAndroid%2Fgradle.properties&type=code

**Comment by ridsameer** [comment]
> > Actually that's unnecessary IMHO. Specifically as previous "tagged version" as mentione in the doc will have the file in the original location
> 
> Most of links in previous version of documentation lead to the `main` branch, so maybe we should change them to point to the release branches instead?
> 
> * https://github.com/search?q=repo%3Afacebook%2Freact-native-website%20ReactAndroid%2Fgradle.properties&type=code

The link seems to lead to an empty list. Not sure if I'm missing something

@cortinico Signed the CLA :)

**Comment by Simek** [comment]
thank you for the CLA sing! 👍 

> The link seems to lead to an empty list. Not sure if I'm missing something

It returns results for me, but this correction might be redundant, since I have updated all of the links in three dedicated PRs a few days ago. As you can see, the link in `main` branch is already corrected:
* https://github.com/facebook/react-native-website/blob/main/docs/image.md?plain=1#L112

One way to make sure that those changes are still needed is to sync up the PR branch with `main`.

**Comment by ridsameer** [comment]
@Simek That's great! I think we can close this one then. Sorry for taking time to get back in between comments :)

**Pull request closed without merging**
