### PR TITLE
Updating links to App Center

### PR DESCRIPTION
**Pull request by elamalani**

### CODE REVIEW

**Comment by elamalani** [comment]
@rickhanlonii @thymikee Please review this PR.

**Comment by elamalani** [comment]
@charpeni Please review.

**Comment by elamalani** [comment]
@thymikee Thanks for approving. When would these changes be live? What's the process?

**Comment by charpeni** [comment]
Hey @elamalani,

Thanks for sending this our way. 

I just updated the versioned docs to be sure your campaign is propagated to every version, we'll wait on the tests to complete, then we'll merge and release this.

It should be live in ~30-40 minutes or so.

Let me know if you have any questions.

**Comment by elamalani** [comment]
Sounds great, thank you!

**Pull request merged**
