### PR TITLE
adding snack player instead of images for flexbox

### PR DESCRIPTION
**Pull request by Stringsaeed**
solves #2163 
replacing images with snack player for better ux

### CODE REVIEW

**Review by espipj — CHANGES_REQUESTED** [review]
Hey, I suggest you to not make changes in the yarn.lock or update the dependencies as it might affect the whole project/repository and just focus on editting the .md files (flexbox in this case). What do you think? 😃

**Comment by Stringsaeed** [comment]
@espipj reverted ✅✅✅

**Comment by Simek** [comment]
@Stringsaeed @espipj Thank you for the comments and adjusting the changes. The yarn lock issue has been addressed in https://github.com/facebook/react-native-website/commit/f41223a7852cda697d2f17c388fe7228a035aec4 commit. I was the last unwanted result after merging series the docs auto generation PRs.

@Stringsaeed I will review the PR changes at the end of the week, currently I have only access to the GH on the phone.

**Review by Simek — APPROVED** [review]
@Stringsaeed thank so much you for the amount of work you have put in this task and the overall quality of examples, great job! 🚀

**Pull request merged**
