### PR TITLE
Update tutorial.md

### PR DESCRIPTION
**Pull request by HughRdgz**
Changed this.props.{NAME} by {this.props.NAME}

### CODE REVIEW

**Review by Simek — COMMENTED** [review]
Hi @HughRdgz, can you explain why you want to change this note? Currently inline code in there looks fine to me. `{NAME}` is referring to the user defined prop, used here as placeholder, the rest of chain should remain unchanged no matter which name has been chosen.

**Comment by HughRdgz** [comment]
> Hi @HughRdgz, can you explain why you want to change this note? Currently inline code in there looks fine to me. `{NAME}` is referring to the user defined prop, used here as placeholder, the rest of chain should remain unchanged no matter which name has been chosen.

maybe I got confused by the brackets, since these are used in code for interpolation.
When I read the documentation I thought it was referring to how you should write the variable when you want that it be interpolated. But now that you put your point of view, it makes sense and now I think maybe I'm wrong.

**Comment by Simek** [comment]
> maybe I got confused by the brackets, since these are used in code for interpolation.
> When I read the documentation I thought it was referring to how you should write the variable when you want that it be interpolated. But now that you put your point of view, it makes sense and now I think maybe I'm wrong.

Template literals requires a dollar sign before the curly brackets:
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

@HughRdgz Maybe we can replace the brackets with other character, but both parentheses `(NAME)` and square braces `[NAME]` probably will cause more confusion. Do you have any other idea?

**Comment by HughRdgz** [comment]
> > maybe I got confused by the brackets, since these are used in code for interpolation.
> > When I read the documentation I thought it was referring to how you should write the variable when you want that it be interpolated. But now that you put your point of view, it makes sense and now I think maybe I'm wrong.
> 
> Template literals requires a dollar sign before the curly brackets:
> 
> * https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
> 
> @HughRdgz Maybe we can replace the brackets with other character, but both parentheses `(NAME)` and square braces `[NAME]` probably will cause more confusion. Do you have any other idea?

What do you thing about angle brackets?

**Comment by Simek** [comment]
> What do you thing about angle brackets?
> It's just an idea

@HughRdgz We can try that, can you update the PR and include change also to the base docs at `/docs/`? 

I will look through the code how often we use this format and if any other notes should be changed too, to preserve the consistency across the website.

**Comment by Simek** [comment]
@HughRdgz It looks like this was the only one place on the website where such placeholder format has been used.

I have also received feedback, that using angle brackets will resemble too much of JSX syntax, so at this moment of time I have changed the placeholder name to more descriptive one, which I hope will also make it more obvious, that it's just a pseudo-code example.

**Pull request merged**
