### PR TITLE
Create 0.62 versioned documentation

### PR DESCRIPTION
**Pull request by kelset**
This is just a PR to add the versioned version of the docs ahead of the 0.62.0 release coming soon ™️

Once this is merged, another PR will need to be created to then move the website to show 0.62 as default, as done in the past like https://github.com/facebook/react-native-website/commit/5a0f9d26acd484212debc0d11971c1a4fbb649fc

### CODE REVIEW

**Comment by Simek** [comment]
I think that `0.62` should be created after #1771 merge. Also as far as I know @rachelnabors have a plan/checklist ready for this new release which include some unconventional steps (like regenerating `0.61` before creating `0.62`).

**Comment by kelset** [comment]
hey Simek thanks for the info, I didn't know anything of that sort 😓

**Comment by thymikee** [comment]
@Simek updating prettier config doesn't seem like a real blocker, right? As soon as there are conflicts, revoking styling changes and running prettier once again is automatic and doesn't involve manual work, so it could land anytime.

**Comment by Simek** [comment]
@thackley It saves additional, redundant work in future. Also as I said before community gathered around `react-native-website` has been discussing about upcoming new version and the way how to  handle this operation properly for the few months (mainly here: #1579) and it will be unfair to discard this work. So in the light of the arguments presented here I see no reason to rush `0.62` generation, but I'm not here to decide.

I hope @rachelnabors will engage in this conversation and post the migration plan/checklist soon.

**Comment by kelset** [comment]
Thanks for the context @Simek 👍 I created the PR because we are getting closer to release 0.62.0 and I got told that everything was 'ok' on the website side so I proceeded with creating this pr.

I've pinged Rachel in the discord and hopefully she'll let us know more soon :)

**Comment by rachelnabors** [comment]
@kelset #1771's Prettier changes are not necessary for 0.62's docs. They change a lot of files and I'd like them to spend a little more time in review for that.

There is a sidebar change that could be nice to get in there that @simek reminded me about: putting deprecation warnings on component and APIs in 0.61 while removing them in 0.62 from the sidebar. But we need a PR for it.

**Comment by kelset** [comment]
ok, then can you approve this PR so that we can proceed with merging? :)

**Comment by rachelnabors** [comment]
I patched up 0.61's sidebars with this PR: https://github.com/facebook/react-native-website/pull/1779 Please re-generate!

**Comment by kelset** [comment]
allright, closing this and recreating!

**Comment by kelset** [comment]
btw @rachelnabors it looks like I'm not allowed to remove this branch from origin 😓

**Comment by kelset** [comment]
New PR with the new cut -> https://github.com/facebook/react-native-website/pull/1782

**Pull request closed without merging**
