### PR TITLE
💃🏽 Animated & PanResponder 👨🏽‍🎤 Snack Examples 👯‍♀️

### PR DESCRIPTION
**Pull request by DaniAkash**
Belongs to https://github.com/facebook/react-native-website/issues/1579

Contains New Function + Class Component examples for the
- Animated API
- PanResponder API
- Animations Guide

Willing to create more examples ﹣ if cool ideas are suggested 😎 💡 🤝

### CODE REVIEW

**Comment by rachelnabors** [comment]
@DaniAkash did you check the Animated and PanResponder APIs to see if they need updating as well?

**Comment by DaniAkash** [comment]
> @DaniAkash did you check the Animated and PanResponder APIs to see if they need updating as well?

Looking into the source code. Will update the PR in 2 days

**Comment by DaniAkash** [comment]
@rachelnabors I looked into the `PanResponder` API & discovered something big! there is a ﹣ 
- [`getInteractionHandle`](https://github.com/facebook/react-native/blob/master/Libraries/Interaction/PanResponder.js#L389)
- And [`clearInteractionHandle`](https://github.com/facebook/react-native/blob/31980094107ed37f8de70972dbcc319cc9a26339/Libraries/Interaction/PanResponder.js#L561) method. 

So does that mean pan handlers are like event listeners that should be cleared on unmount?
If that's the case I'll create a new PR addressing it 👍

**Comment by rachelnabors** [comment]
I would imagine so! @DaniAkash can you handle?

**Comment by DaniAkash** [comment]
It's gonna take some time. I'll raise the PR!

**Comment by DaniAkash** [comment]
> I would imagine so! @DaniAkash can you handle?

@rachelnabors the panresponder events are configured to be handled internally so even if the event handler methods are there, they are not exposed to the users. 

Which also means the API is up-to-date and doesn't need another PR

**Pull request merged**
