### PR TITLE
Remove references to outdated lifecycle hooks

### LINKED ISSUE #844: Remove references to deprecated lifecycles
We have some references to `componentWill*` which are deprecated lifecycles.

### Native Modules Android

> JavaScript modules can then register to receive events by addListenerOn using the Subscribable mixin.

```js
import { DeviceEventEmitter } from 'react-native';
...

var ScrollResponderMixin = {
  mixins: [Subscribable.Mixin],


  componentWillMount: function() {
    ...
    this.addListenerOn(DeviceEventEmitter,
                       'keyboardWillShow',
                       this.scrollResponderKeyboardWillShow);
    ...
  },
  scrollResponderKeyboardWillShow:function(e: Event) {
    this.keyboardWillOpenTo = e;
    this.props.onKeyboardWillShow && this.props.onKeyboardWillShow(e);
  },
```

> You can also directly use the DeviceEventEmitter module to listen for events.

```js
...
componentWillMount: function() {
  DeviceEventEmitter.addListener('keyboardWillShow', function(e: Event) {
    // handle event.
  });
}
...
```

#### Location

- [/docs/native-modules-android.md](https://github.com/facebook/react-native-website/blob/852a035c116fdcdf78ffa1ba53d7499c2bf3e3a9/docs/native-modules-android.md)

#### What to do?

- [x] The first part on mixins could be simply removed as mixins are not the future (sorry gaearon).
- [x] Then `componentWillMount` could be replaced with `componentDidMount` using the usual ES6 method declaration without `componentWillMount: function() { }`.

### Communication iOS & Android

> **Note:** Currently, JS functions `componentWillReceiveProps` and `componentWillUpdateProps` of the top level RN component will not be called after a prop update. However, you can access the new props in `componentWillMount` function.

#### Location

- [/docs/communication-ios.md](https://github.com/facebook/react-native-website/blob/e0570a5ea4ea903b66b40ea21bb4fad5f204a325/docs/communication-ios.md)
- [/docs/communication-android.md](https://github.com/facebook/react-native-website/blob/0d36c27ef53c78f706fc2e303f0ca26bdb925217/docs/communication-android.md)

#### What to do?

- [ ] `functions` these are more a lifecycle than a "function".
- [x] `componentWillReceiveProps` is deprecated without a direct replacement, could probably be simply removed.
- [ ] `componentWillUpdateProps ` doesn't seems like a valid lifecycle? 🤔
- [x] `componentWillMount` could probably be replaced with `componentDidMount` which will also be called on the initial render (or native props changed in this case). Also, `static getDerivedStateFromProps` is also available to compute a state from props, both on the initial mount and on subsequent updates.

### PR DESCRIPTION
**Pull request by jamesgeorge007**
Related to #844 
> Updated occurences of outdated lifecycle methods like `componentWillMount` to `componentDidMount`

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
@charpeni Kindly suggest the required changes :thinking:

**Comment by jamesgeorge007** [comment]
@charpeni What do you think?

**Comment by charpeni** [comment]
@jamesgeorge007 sorry for the delay, I'll check this tomorrow.

**Comment by charpeni** [comment]
Thanks for doing that, I edited your PR to remove `Close` as two tasks are remaining.

**Pull request merged**
