### PR TITLE
Generate 0.67 version of the docs

### PR DESCRIPTION
**Pull request by kelset**
This PR simply generates the version 0.67 of the documentation ahead of the release of 0.67.0 that should happen over the next 7 days.

It contains also some changes to the yarn.lock that were present on my local machine (after doing a clean and a yarn) so I guess they might be changes we want to commit? Let me know, in case I can just revert that commit and leave just the generated 0.67 stuff.

It will have to be merged along with: https://github.com/facebook/react-native-website/pull/2933

### CODE REVIEW

**Comment by fabriziobertoglio1987** [comment]
I went through the process of setup on Ubuntu 20.04 yesterday of next version to build react-native from source.
I see no issues with the documentation, I was thinking of updating [next](https://deploy-preview-2926--react-native.netlify.app/docs/next/environment-setup) page to include https://discord.com/channels/514829729862516747/514832058955202561/913495885537767474

>PSA: We just bumped AGP to 7.x and compile/targetSdkVersion to 31 (Android 12)
>This means that you need to hava Java11 to build the react-native project. 
>From RN 0.68, new apps will require Java11 as well. Existing apps are not affected for now, but we highly encourage you to update your local JDK

If you want I can publish a pr with this updates. Thanks a lot

**Review by Simek — APPROVED** [review]
Thanks @kelset! 👍 

> It contains also some changes to the yarn.lock that were present on my local machine (after doing a clean and a yarn) so I guess they might be changes we want to commit? Let me know, in case I can just revert that commit and leave just the generated 0.67 stuff.

Lock changes are fine, only the old resolution version have been removed for the few packages, there is no real dependency changes.

**Comment by kelset** [comment]
@fabriziobertoglio1987 I think that an alert/callout could be added in the docs (as a separate PR from this) but in a shorter version, like so:

> From RN 0.68, new apps will require Java11 as well. Existing apps are not affected for now, but we highly encourage you to update your local JDK

To avoid confusion around the state of the codebases for "latest" (which from next week will be 0.67 which is not yet affected by the bump)

**Comment by cortinico** [comment]
> I think that an alert/callout could be added in the docs (as a separate PR from this) but in a shorter version, like so:

Agree. This reminds me that we haven't merged yet this: https://github.com/facebook/react-native-website/pull/2800 - Maybe we can add a info box there?

**Comment by kelset** [comment]
Just to clarify once again - the Java 11 conversation only affects React Native >=0.68 so it's not a blocker for 0.67 docs, correct @cortinico?

**Comment by kelset** [comment]
updated the PR to integrate the changes merged in https://github.com/facebook/react-native-website/pull/2800 in the 0.67 versioned docs

**Comment by cortinico** [comment]
> the Java 11 / AGP 7 conversation only affects React Native >=0.68 so it's not a blocker for 0.67 docs, correct @cortinico?

Correct. JDK 11 is going to be a **requirement** on >=0.68

**Comment by fabriziobertoglio1987** [comment]
I don't see a pr for [linux version next](https://reactnative.dev/docs/next/environment-setup).
I'll prepare a Pull Request.
I'm on Linux and I already tested the setup several times and will test it again.
Thanks a lot.

**Pull request merged**
