### PR TITLE
doc: add console.debug, console.groupCollapsed to list of console APIs

### PR DESCRIPTION
**Pull request by ashwinkumar6**
Update list of console APIs to also reflect `debug` and `groupCollapsed`

### CODE REVIEW

**Comment by ashwinkumar6** [comment]
CLA has been signed, thank you

**Review by Simek — COMMENTED** [review]
Hello @ashwinkumar6, thank you for the docs update! 👍 

Can you backport the changes also to the versioned docs, since looks like those methods were added quite a while ago.
* https://github.com/facebook/react-native-website?tab=readme-ov-file#versioned-docs

Refs:
* https://github.com/facebook/react-native/pull/18555
* https://github.com/facebook/react-native/blob/a80674fc7c04da5c8630dc4bfc63904fd38e9e71/packages/polyfills/console.js#L556-L568

**Comment by ashwinkumar6** [comment]
Thanks for the references @Simek, 
Updated

**Review by Simek — APPROVED** [review]
Thanks for the backports, let's ship this! 🚀

**Pull request merged**
