### PR TITLE
Added osedea blog post on tips on how to speed up development

### PR DESCRIPTION
**Pull request by adrienthiery**
📝

### CODE REVIEW

**Comment by charpeni** [comment]
Sorry for the delay, we've not forgotten you. Hector or I will try to review this shortly.

On a side note, I just found this page while searching on Osedea: https://osedea.com/en/neeeed. I'm glad to see a Montreal based company that contribute as much to the React Native community, that's much appreciated thank you. 😃

**Comment by adrienthiery** [comment]
Hi Nicholas,

Thanks a lot, we are trying our best 🙂

**Comment by adrienthiery** [comment]
Hi @charpeni,

Any news on that ? 🙂

**Comment by charpeni** [comment]
I'll check this during the weekend 🙂.

**Comment by cpojer** [comment]
Thank you for this blog post. Unfortunately I don't think the React Native blog is the right place for this type of post. Would you mind putting this on your company's blog instead?

**Pull request closed without merging**
