### PR TITLE
Update alert.md

### PR DESCRIPTION
**Pull request by Vishnukr1101**
Button alignment updated

### CODE REVIEW

**Review by Simek — CHANGES_REQUESTED** [review]
Hi @Vishnukr1101, thank you for the example update! 👍 

Can you use `StyleSheet` (like in other examples) instead of inline styles? 🙂

**Review by Vishnukr1101 — COMMENTED** [review]
stylesheet added

**Comment by Simek** [comment]
Thank you! Now the CLA Sign has left to make this PR green. 🚀 

Also, if you want, you can updated the latest versioned docs, so the fix will appear in the default selected docs version:
* https://github.com/facebook/react-native-website/blob/master/website/versioned_docs/version-0.64/alert.md

**Comment by Simek** [comment]
@Vishnukr1101 This PR was valid, why you have closed it and removed the branch? 

Unfortunately I'm not able to reopen this PR now.

**Comment by Vishnukr1101** [comment]
> 
> 
> @Vishnukr1101 This PR was valid, why you have closed it and removed the branch?
> 
> Unfortunately I'm not able to reopen this PR now. 😅

facebook-github-bot was not passing CLA Sign check.

**Review by Simek — APPROVED** [review]
LGTM, thank you for the review updates! 👍 

As stated in the bot comment:
> The tagging process may take up to 1 hour after signing.

So you need to give it a while, closing issue won't help much with bot delay. 😉

**Pull request merged**
