### PR TITLE
Update state.md

### PR DESCRIPTION
**Pull request by sunnylqm**
Since the example is using hooks, it does not make sense to mention constructor and setState

### CODE REVIEW

**Comment by Simek** [comment]
Hi @sunnylqm! I'm not sure if removing the sentence is the right way to fix this issue. I rather would like to see the addition of class component example and tabs. Then the note/sentence could be placed inside the class component tab to not confuse those who are using the functional approach.

Also there are more references to the class component, for example:
> When setState is called, BlinkApp will re-render its Component. By calling setState within the Timer, the component will re-render every time the Timer ticks.

I think that @rachelnabors should decided what's the best approach there(since I'm not familiar with this page and it's purpose).

BTW. How you have landed on this page? I'm asking since it's out of the sidebar right now. Was it the App template link, search result or maybe something else?

**Comment by sunnylqm** [comment]
So is this doc going to be removed? I am running a translation mirror site for this so I will going through all the docs once a while.

**Comment by Simek** [comment]
@sunnylqm I don't know what's the purpose or what is the future of this page. 

> BTW. How you have landed on this page? I'm asking since it's out of the sidebar right now. Was it the App template link, search result or maybe something else?
Can you answer the question above?

And to be honest you could wait with the issue closure until @rachelnabors response 😉

**Comment by sunnylqm** [comment]
I simply read all the docs in the repo and do some typo fix sometimes. 
> I am running a translation mirror site for this so I will go through all the docs once in a while.

**Pull request closed without merging**
