### PR TITLE
Code refactor and add method parsing

### PR DESCRIPTION
**Pull request by ayushjainrksh**
## Summary
The PR is part of an effort to add the latest changes to the script merged in #2129. The script requires #2143 to fix the dependency that was removed in [this](https://github.com/facebook/react-native-website/pull/2129/commits/f38f62f680043b1b65b9043e8eb40085b4a7ef62#diff-07f3a4647460e74f9514d8def137963aL49) commit by mistake and is responsible for handling the [encoding of the strings](https://github.com/facebook/react-native-website/blob/6e41a04f987b8161baaa578bb3334857e4896348/website/scripts/sync-api-docs/propFormatter.js#L38).

The project is a part of MLH Fellowship program and involves the automatic generation of the website docs from code comments and flow types as the end result.

To learn more about the project you can visit the project wiki: 
- [Project Details](https://github.com/MLH-Fellowship/0.4.x-projects/wiki/React-Native-Flowtype-API-Docs-Generator)
- [RN Docs Standards](https://github.com/MLH-Fellowship/react-native/wiki/RN-Docs-standards)

## Changes
* **Code Refactoring**
  * Separate files for props(`propFormatter.js`) and methods(`methodFormatter.js`) formatting.
  * Add reusable functions to `utils.js`.
  * Delete file `titleToId.js` and move function to `utils.js`
  * Eliminate unused imports.
* **New Features**
  * Add method parsing funtionality.
  * Support more prop types and update `magic.js`.
* **Bug fixes**
  * Use `findAllComponentDefinitions` resolver instead of `findExportedComponentDefinition`.
  * Fix description parsing (with SnackPlayer).
 
## Preview (**generated with scripts**):
- [Button](https://reactnativedocs.netlify.app/docs/next/button)
- [ActivityIndicator](https://reactnativedocs.netlify.app/docs/next/activityindicator)
- [Switch](https://reactnativedocs.netlify.app/docs/next/switch)
- [Flatlist](https://reactnativedocs.netlify.app/docs/next/flatlist)
- [KeyboardAvoidingView](https://reactnativedocs.netlify.app/docs/next/keyboardavoidingview)
- [RefreshControl](https://reactnativedocs.netlify.app/docs/next/refreshcontrol)
- [ScrollView](https://reactnativedocs.netlify.app/docs/next/scrollview)

## Changelog
[Internal]

### CODE REVIEW

**Comment by motiz88** [comment]
This PR requires https://github.com/facebook/react-native-website/pull/2143 to work, right? This fact should be called out in the PR summary.

**Comment by ayushjainrksh** [comment]
Thanks for pointing it out. I've updated it now.

**Comment by Simek** [comment]
@motiz88 What's the status of this PR?

**Comment by Simek** [comment]
@ayushjainrksh Would you like to update the PR to match latest workspace changes in the repository?

**Comment by ayushjainrksh** [comment]
@Simek Yeah sure.

**Comment by ayushjainrksh** [comment]
@Simek This should do. I've tested the script to generate some components and also pushed a minor update to fix a few issues. I found that the script would need some more updates because of the Docusaurus update. Although the script works fine we'd need to change the HTML in markdown to JSX format apparently used by the new Docusaurus. It can be done in a separate PR when this gets merged. Let me know how'd you like to proceed.

**Comment by Simek** [comment]
> Although the script works fine we'd need to change the HTML in markdown to JSX format apparently used by the new Docusaurus.

Yup, Docusuaurs V2 uses [MDX](https://mdxjs.com/) instead of pure Markdown.

> Let me know how'd you like to proceed.

I'm going to test the changes locally and if workspace is fine and `sync` script succeeds this PR can be merged. Feel free to work on the updates in the separate PR.

**Review by Simek — APPROVED** [review]
LGTM, thank you for working on the sync APIs script! 👍

**Comment by ayushjainrksh** [comment]
Thanks for merging this PR. `sync` command runs fine.

**Pull request merged**
