### PR TITLE
docs: measureLayout() with native node handler is obsolete when using new architecture

### PR DESCRIPTION
**Pull request by LunatiqueCoder**
```
 (NOBRIDGE) LOG  Bridgeless mode is enabled
 (NOBRIDGE) ERROR  Warning: ref.measureLayout must be called with a ref to a native component.
```

`measureLayout()` with `relativeToNativeNode` handler (instead of reference) seems to be **OBSOLETE** when using the new architecture.

### CODE REVIEW

**Comment by javache** [comment]
Can you update this in the latest docs instead of the 0.75 version?

**Comment by LunatiqueCoder** [comment]
Added for 0.76. Let me know if I should remove the `version-0.75` change as well.

**Comment by Abbondanzo** [comment]
Keeping the `version-0.75` is great. Could you make the same changes to versioned docs for 0.76 too?

**Comment by LunatiqueCoder** [comment]
@Abbondanzo Hmm, so weird. Pressing the "Edit this page"on the docs seems to be leading me to the wrong place on 0.76.

Updated, hope everything's ok now.

**Comment by Abbondanzo** [comment]
> @Abbondanzo Hmm, so weird. Pressing the "Edit this page"on the docs seems to be leading me to the wrong place on 0.76.
> 
> Updated, hope everything's ok now.

Good callout, the "Edit this page" button will only point to the latest version of the docs and not the version you're looking at, but we can update that. Thanks for making these last changes so quickly!

**Pull request merged**
