### PR TITLE
StickyHeaderIndices updated with missing info

### PR DESCRIPTION
**Pull request by Sargnec**
StickyHeaderIndices updated.

### CODE REVIEW

**Review by Simek — CHANGES_REQUESTED** [review]
Hi @diogeneshamilton, thank you for the docs update! 👍 

Can you also update the current docs file located in [`/docs`](https://github.com/facebook/react-native-website/tree/master/docs) directory (besides the versioned page)? 

Also the added sentence sounds a bit off, please try to rephrase it.

**Comment by Sargnec** [comment]
@Simek This is my first time contributing. Sorry if I made a mistake

**Comment by Simek** [comment]
> @Simek This is my first time contributing. Sorry if I made a mistake

Not a problem, take all the time you need. 🙂 You can find the guide about the site setup, structure and how to test changes in the Readme file - https://github.com/facebook/react-native-website#%EF%B8%8F-getting-started

**Review by Simek — APPROVED** [review]
Thank you for the changes!

**Pull request merged**
