### PR TITLE
Sorted in alphabetical order settings.md

### PR DESCRIPTION
**Pull request by abhinavsagar**
Updated settings.md

### CODE REVIEW

**Comment by raajnadar** [comment]
"sorting a alphabetically" what? Give some informative title like `updated componentName.md`

**Comment by abhinavsagar** [comment]
Sorry for any miscommunication.

**Comment by raajnadar** [comment]
I was talking about the title.

**Comment by abhinavsagar** [comment]
Got it.

**Comment by rickhanlonii** [comment]
Hey @abhinavsagar, thanks for helping us sort these!

**Pull request merged**
