### PR TITLE
Update scrollview.md

### PR DESCRIPTION
**Pull request by Smartech-git**
Fixed a grammatical error in ScrollView Docs

### CODE REVIEW

**Comment by cortinico** [comment]
I don't think that's a typo actually. We might reword the sentence to make it clearer

**Comment by Smartech-git** [comment]
> I don't think that's a typo actually. We might reword the sentence to make it clearer

rewording to make it clearer will be much better

**Comment by cortinico** [comment]
> rewording to make it clearer will be much better

Are you up for suggesting a better wording? :)

**Comment by Smartech-git** [comment]
> Are you up for suggesting a better wording? :)

Handler function is passed with two parameters: `(contentWidth, contentHeight)`


<h3>what do you think?</h3>

**Comment by cortinico** [comment]
> > Are you up for suggesting a better wording? :)
> 
> Handler function is passed with two parameters: `(contentWidth, contentHeight)`
> ### what do you think?

Maybe:
```
The handler function will recieve two parameters: the content width and content height.
```

**Comment by Smartech-git** [comment]
Ok, that is better. 🙂

**Review by cortinico — APPROVED** [review]

**Comment by cortinico** [comment]
@Smartech-git can you sign the CLA otherwise we can't merge this PR?

**Comment by Smartech-git** [comment]
> @Smartech-git can you sign the CLA otherwise we can't merge this PR?

I've signed the CLA 👍

**Review by Simek — APPROVED** [review]
Thank you for the contribution, LGTM! 👍

**Pull request merged**
