### PR TITLE
Overflow issue in React Native examples (Expo)

### PR DESCRIPTION
**Pull request by jvitoroc**
When width is set to 880px, it overflows my viewport.
My screen is 1024px wide.

### CODE REVIEW

**Comment by hramos** [comment]
Can you add a test plan to your PR?

**Comment by jvitoroc** [comment]
I'm not familiarized with pull request guidelines.

**Comment by charpeni** [comment]
Hey @jvitoroc,

You can just describe how you've tested your changes and how it doesn't break everything.

**Comment by cpojer** [comment]
Thanks! We'll be overhauling the website more generally so I'm gonna close this PR.

**Pull request closed without merging**
