### PR TITLE
Update the way for Expo projects to enable New Architecture

### PR DESCRIPTION
**Pull request by Kudo**
# Why

Follow up https://github.com/reactwg/react-native-new-architecture/discussions/127#discussioncomment-5688489

# How

Given that we are now support New Architecture in most cases, only exceptions in some expo-modules like expo-dev-client. We may able to support more all in Expo SDK 49. I am revising the wording as "How to enable New Architecture in Expo projects".

### CODE REVIEW

**Comment by Kudo** [comment]
my first pr at react-native-website. let me know whether that makes sense to you. cc @cortinico @Simek

**Comment by Simek** [comment]
Is this a follow up for #3701 or it is its replacement? 😄

**Comment by Kudo** [comment]
cool, didn't notice there's #3701. thanks for that.
@brentvatne do you think if we would like to mention how to enable new architecture on expo porjects a little bit?

**Review by cortinico — APPROVED** [review]

**Comment by cortinico** [comment]
I'll leave this to you folks to decide the best recomendation for users

**Comment by Kudo** [comment]
having a discussion with Brent in a call. i am closing this pr and let Brent to update in #3701. thanks!

**Pull request closed without merging**
