### PR TITLE
Update security.md

### PR DESCRIPTION
**Pull request by Ricardo-Paul**
add missed word

### CODE REVIEW

**Review by Simek — COMMENTED** [review]
Hi @Ricardo-Paul,

I'm not a native speaker, but I think that current sentence is correct. 

As far as I can understand, this is a hint for the developers, which suggest to choose the security solution based on the amount of sensitive data that your app is using.

**Comment by Ricardo-Paul** [comment]
Hi @Simek, this is surely a wrong interpretation on my side, thank you.

**Comment by Simek** [comment]
@Ricardo-Paul No problem, I'm happy that I was able to help. Is it fine to close this PR? 🙂

**Comment by Ricardo-Paul** [comment]
Of course @Simek.

**Pull request closed without merging**
