### PR TITLE
Migrate React Native website to Docusaurus V2

### LINKED ISSUE #2054: Content of the sidebar cannot be fully viewed
## Description

The content of the navigation sidebar that is displayed on all pages cannot be fully viewed, as it's being pushed down by the Announcement Banner.

Screen Shot 2020-07-15 at 17 15 55

Notice in the image above that the section Guides (iOS) is not visible. Removing the announcement banner specific code (top padding on the sidebar and the HTML elements) fixes the issue.

Perhaps the contents of the sidebar should be fully scrollable or the presence of the announcement banner should apply extra styling to the sidebar

Edit: This issue is reported in Chrome Version 83.0.4103.116 (Official Build) (64-bit) from a Macbook Pro with a fixed Dock. In Safari and Firefox I can scroll the content.

## Documentation version

0.63.0

### LINKED ISSUE #2208: Request for Dark Theme with theme toggle for developers
This is just a small feature request. Would do a world good.

Introduction
I'd like to suggest implementing a Dark theme toggle switch, the same way Redux website https://redux.js.org/ and Redux Toolkit website https://redux-toolkit.js.org/ have that small toggle switch at the right upper corner of the top navbar.

Details
It really hurts your eyes when you read other Redux documents with dark theme and suddenly React Native website is bright white, especially while integrating redux.

Discussion points
Would do a lot good for the community

### PR DESCRIPTION
**Pull request by Simek**
This PR migrates the React Native website to Docusaurus V2. 

This is an effect of collaboration with @slorber and MLH Docusaurus team (@darshkpatel & @teikjun).

It is the initial import, rebased against current `master` in the main repository.

Refs: #2146, #2139 

Fixes #2208, Fixes #2054

### Preview

* https://deploy-preview-2263--react-native.netlify.app

### Noticeable changes for website user
* SPA - reduced page load times, more fluid navigation
* additional dark theme and theme toggle (dark theme Snacks too)
* build in tabs sync
* Snacks appears on mobile without the preview but with link to open example in Expo app
* blog posts are now searchable
* code blocks content can be copied by click - "Copy" button appears on hover
* old versions and `next` page have a notice for users that they are reading old or upcoming version of the page

### Noticeable changes for contributors/maintainers
* announcement bar support out of the box
* MDX fragments - which allows to split content and helps to maintain large pages (example: Environment Setup)
* extended page customizability and theme components swizzling
* improved build times
* still growing set of ready to use plugins - https://v2.docusaurus.io/docs/using-plugins/
* `<!--truncate-->` tag for blog posts to hide the details on the post list, blog posts tags

#### You can read more about V2 features and changes in the official documentation:
* https://v2.docusaurus.io/docs/

### CODE REVIEW

**Comment by charpeni** [comment]
Deploy preview for *react-native* failed.

Built with commit aea653ec26394355b19976ca2ba2ebdba157d0a1

https://app.netlify.com/sites/react-native/deploys/5f8f292c26a6970007f559df

**Comment by charpeni** [comment]
Deploy preview for *react-native* failed.

Built with commit e567208fe6bc26569eb27f474b7eedcd9603d82b

https://app.netlify.com/sites/react-native/deploys/5f8f2a7e8e7e780008b67db1

**Comment by Simek** [comment]
As posted in the comment above deploy preview is available in here:
* https://deploy-preview-2263--react-native.netlify.app

Feel free to report any spotted issues or problems.

**This PR should NOT be merged before the V1 based archive is deployed!**

**Comment by Simek** [comment]
The `archive` branch website deploy has been set up and RN Archive is available under https://archive.reactnative.dev/ URL.

In theory, having V1 archive up and running makes this PR ready to review and merge 🙂

**Comment by cpojer** [comment]
What are the next steps for this PR? Can you make a checklist in the summary of this PR? Let me know when you need me for final review.

**Comment by Simek** [comment]
> What are the next steps for this PR? Can you make a checklist in the summary of this PR? Let me know when you need me for final review.

@cpojer I have posted all the steps within the migration plan last week. Since V1 Archive is deployed this PR should be ready to merge. The commits that appears in this PR lately are just a small tweaks which should not affect the functionality and break the deployment in any way.

Currently we are only not sure if V2 deploy will work from `master` (after the merge) but there was no way to check this earlier, we are ready to hot fix issues on merge. 

When the V2 deploy will be finished we need to ask Algolia to update the search index and recrawl the website. There are also several minor checks that need to be done after the deployment, for example:  if the Google Analytics events are tracked correctly.

**Comment by cpojer** [comment]
Thanks for clarifying. I will review it tomorrow and merge it then.

**Review by cpojer — APPROVED** [review]
Amazing, what a huge amount of work. Thank you so much for making this happen.

**Comment by sunnylqm** [comment]
@Simek I found some docs are reverted to an older version like this one https://github.com/facebook/react-native-website/commit/e622c6a43246bb354e7aa60768d7af20fb82b0fc#diff-941914e9c6da4d386c78dcde541e7cc9be34624e543dfccbad380409d8e81813L152-L162

**Comment by Simek** [comment]
Hi @sunnylqm, it is not clear what changes are exactly missing, remember that the tabs code has changed so the diff might be misleading. 

Please check the page file in the `master` docs and let me know if problem occurs in there - https://github.com/facebook/react-native-website/blob/master/docs/building-for-tv.md.

In a meanwhile I will compare `master` with `archive` branch and try to find the issue.

**Comment by sunnylqm** [comment]
@Simek That doc in `master` is incorrect (older) after the migration commit as I showed above

**Comment by Simek** [comment]
@sunnylqm Can you show me somehow where exactly is the issue which you are referring? Can you quote the missing paragraph or sentence on the new site?

At the first glance content on https://reactnative.dev/docs/building-for-tv and https://archive.reactnative.dev/docs/building-for-tv pages looks the same.

**Comment by sunnylqm** [comment]
I think maybe it's because the master version did not build into versioned doc. For the content, it's obvious `tabbarIOS` and `ListView` are deprecated long time ago.

**Comment by Simek** [comment]
> I think maybe it's because the master version did not build into versioned doc. For the content, it's obvious `TabBarIOS ` and `ListView` are deprecated long time ago.
> 
> So if you take the doc from versioned folder, there might be more inconsistence (not all doc changes go into version folder immediately)

Sorry, but I don't understand you.

My last idea is that you are looking for additional known issues on Android TV which were only applied to the `next` docs before the migration, so they are only visible in the `next` docs: https://reactnative.dev/docs/next/building-for-tv

**Comment by sunnylqm** [comment]
@Simek See this commit https://github.com/facebook/react-native-website/commit/6677d7a8e83cfeaf17fc57045fa6f140046b24f1#diff-941914e9c6da4d386c78dcde541e7cc9be34624e543dfccbad380409d8e81813
It's reverted, isn't it?

**Comment by sunnylqm** [comment]
If you take the doc from [versioned folder](https://github.com/facebook/react-native-website/tree/master/website/versioned_docs) and copied them back to [master](https://github.com/facebook/react-native-website/tree/master/docs), some changes that haven't build will get lost. Do I make myself clear?

**Comment by Simek** [comment]
@sunnylqm You should mention #2126 at the beginning. 😉 Now I can clearly see and can confirm that this change has been somehow lost during the migration. Would you like to prepare PR to fix this?

> If you take the doc from versioned folder and copied them back to master, some changes that haven't build will get lost

The versioned docs were not copied into `next` docs during the migration. You can check the whole process in the fork created specially for this migration: https://github.com/react-native-website-migration/react-native-website

**Comment by sunnylqm** [comment]
And i noticed the edit link now changed to versioned doc(it was linked to master before), which may not be a good choice.
For a common pattern we should commit to master first then cherrypick to current release right?(either automatically or manually)

**Comment by Simek** [comment]
This is how Docusuaurs V2 "Edit Page" links works and there is no option to change that at this moment. We can always create PR for that, but I'm personally looking at this as an improvement. 

When all links were leading to the `next` version potential contributors were often confused, because they want to fix something on the page they are reading, but after "Edit Page" link click they were seeing different page content or the issue they were looking for was missing on the GitHub file which was opened.

**Comment by sunnylqm** [comment]
The question is that what's the cause for that lost?(I don't know what to check on that migration repo)  If it's not copied from versioned docs, the only possibility I can come up with is it's copied from a snapshot on master? 
Either way I am worrying about more commits may lost.

**Comment by slorber** [comment]
@sunnylqm I agree with you and it's also a problem for docusaurus website.
I want to add an option so that we can configure the edit link of each version independently.
You can make the RN 0.63 (latest) target the master docs in priority for example. I'd also prefer to edit the master docs in such case because if we merge by mistake a PR that only target RN. 0.63 we end up loosing the info for RN 0.64

This is also needed because some of our users are assembling md files from external repos, git submodules etc... Also we'll explore how to handle git-based CMS tools like Forestry/Tina/NetlifyCMS, in which case the edit link may rather target the edition UI instead of the git file.

So, it's not ready today but it's something we'll definitively support soon

**Pull request merged**
