### PR TITLE
Remove extra prefix in template name

### PR DESCRIPTION
**Pull request by itrelease**

### CODE REVIEW

**Comment by cpojer** [comment]
This didn't work for me:

```
✖ Copying template
error Error: Cannot find module '/var/folders/mt/v298rnsj1j1_vjq654qfv_mr0000gn/T/rncli-init-template-ploLP0/node_modules/typescript/template.config'
Require stack:
- /Users/cpojer/.npm/_npx/53677/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/init/template.js
- /Users/cpojer/.npm/_npx/53677/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/init/init.js
- /Users/cpojer/.npm/_npx/53677/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/init/index.js
- /Users/cpojer/.npm/_npx/53677/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/index.js
- /Users/cpojer/.npm/_npx/53677/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js
- /Users/cpojer/.npm/_npx/53677/lib/node_modules/react-native/cli.js
```

I guess it's better to keep the prefix for now?

**Comment by dac09** [comment]
Weird - works on one machine with
```
npx react-native init TSProject --template typescript
```
but not another. Using npx so the version shouldn't be an issue?

**Comment by cpojer** [comment]
Just tried the exact same command again and it doesn't work.

**Comment by cpojer** [comment]
Let's keep it as-is for now.

**Pull request closed without merging**
