### PR TITLE
Use diff syntax for codeblocks

### PR DESCRIPTION
**Pull request by cortinico**
I've updated several codeblocks in the migration guide to use the `diff` syntax + I've added several missing `title='...'` so it's cleared of which file we're talking about.

### CODE REVIEW

**Comment by cortinico** [comment]
> which had to be manually removed after paste,

Yup I noticed the same. What is worse is that also selecting multiple lines carries over the `+`.

> (there is // highlight-start/end but it's just a visual lines highlight, no ability to alter the appearance or leave a comment - [docusaurus.io/docs/next/markdown-features/code-blocks#line-highlighting](https://docusaurus.io/docs/next/markdown-features/code-blocks#line-highlighting))

Maybe I can update those diff which are involving more than say 5 lines, to use this feature instead, wdyt?

**Comment by slorber** [comment]
On the docusaurus side, we'd definitively be interested to be able to:
- have syntax highlighting on diff codeblocks
- make it easier to copy working code from diff

We had a few issues in our own tutorials where users suggested to move back from diff to regular code block:
- https://github.com/facebook/docusaurus/pull/6833
- https://github.com/facebook/docusaurus/issues/4698


cc @Josh-Cena

**Comment by Josh-Cena** [comment]
> have syntax highlighting on diff codeblocks

This can be done with a [Prism plugin](https://prismjs.com/plugins/diff-highlight/). I tried a while back by swizzling `prism-include-languages` but no luck, and didn't bother making it work.

> make it easier to copy working code from diff

This would be done through a string sanitization before passing to `copyToClipboard`, but last time when https://github.com/facebook/docusaurus/issues/4698 was brought up, we decided that if a diff code block needs to be copied, it should probably be a normal code block instead. The valid use-cases of `diff` are those that are purely illustrative, like https://docusaurus.io/docs/sidebar/autogenerated#using-number-prefixes

Not sure if we necessarily want to handle `diff` specially—should we copy the `-` lines, or only the `+` lines? I mean, the entire purpose of `diff` is to show a _process_, not a _result_...

**Comment by slorber** [comment]
> Not sure if we necessarily want to handle diff specially—should we copy the - lines, or only the + lines? I mean, the entire purpose of diff is to show a process, not a result...

Somehow agree but users expect this to work apparently. Also there's a copy button on :hover so it's a bit misleading. Maybe we should just remove that copy button for diff code blocks?

**Comment by Josh-Cena** [comment]
> Somehow agree but users expect this to work apparently. Also there's a copy button on :hover so it's a bit misleading. Maybe we should just remove that copy button for diff code blocks?

Doesn't sound like a bad idea.

**Comment by cortinico** [comment]
What's the final decision here @Simek ? How do you feel about using the `diff` syntax only to changes of 3/4 lines?

**Comment by Simek** [comment]
Sound good to me! 👍 It's not a blocker anyway, since there is no ideal solution yet.

P.S. Unfortunately I was not able to look at the Prisma plugin port/addition yet, but I have this in my schedule for this month.

**Comment by Josh-Cena** [comment]
@Simek Recently I've come to known that the Prism plugin actually won't work with `prism-react-renderer` which Docusaurus uses. See https://github.com/FormidableLabs/prism-react-renderer/issues/90

**Comment by Josh-Cena** [comment]
IDK—I feel like this is quite opinionated and not necessarily correct, and it would be dangerous for us on a framework level to assume what users want when they use `diff`—what if they just want to illustrate, well, a diff?

In https://github.com/typescript-eslint/typescript-eslint/pull/5099 I made the removed lines non-selectable and non-copyable, which suits that particular use-case, but is not a fair assumption to make.

**Comment by slorber** [comment]
@Josh-Cena I don't think many wouldn't want this behavior in practice

What if we made diff behavior opinionated automatically, but allow another metastring to opt-out?

Like `diff preserve` vs `diff`?

This requires to document it, but that seems fine

**Comment by Josh-Cena** [comment]
I'm ok with that, sure... If we can design it well.

**Comment by cortinico** [comment]
I'm abandoning this. The docs changed so much that this is not relevant. We've been using the Diff blocks sporadically in the new docs + we reduce the amount of changes needed for the new arch so this is probably not relevant anymore.

**Pull request closed without merging**
