### PR TITLE
Update scrollview.md to reflect duration argument

### PR DESCRIPTION
**Pull request by dannycochran**
https://github.com/facebook/react-native/pull/17422 adds the ability to control the duration of a scrollView animation, for Android only.

#17422

### CODE REVIEW

**Comment by hramos** [comment]
Will need to wait until that PR is merged.

**Comment by dannycochran** [comment]
Synced documentation here with the comments in the ScrollView.js code from this PR:

https://github.com/facebook/react-native/pull/17422

**Comment by charpeni** [comment]
Thanks, can you also rebase your changes on master? We'll have a working deploy preview.

**Comment by dannycochran** [comment]
@charpeni done, I think.

**Comment by cpojer** [comment]
I'm landing this change to RN imminently.

**Comment by avinashpatnaik** [comment]
Was this released? It doesnt seem to work in Android when I get the react-native from 'https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz'. I checked the ReactScrollViewCommandHelper(I am assumimg this is where the changes happened) and there is no duration component available yet. Am I missing something here?

**Pull request merged**
