### PR TITLE
docs: update view text

### PR DESCRIPTION
**Pull request by lukasjengo**
Hey, noticed that View component prop definition texts were off in some places.

### CODE REVIEW

**Comment by cortinico** [comment]
We use this same wording across the website thought, I'm unsure we should be merging this:

```
rg "Whether "
refreshcontrol.md
74:Whether the view should be indicating an active refresh.
94:Whether the pull to refresh functionality is enabled.

sectionlist.md
344:- 'animated' (boolean) - Whether the list should do an animation while scrolling. Defaults to `true`.

view.md
378:Whether this `View` should be focusable with a non-touch input device, eg. receive focus with a hardware keyboard.
445:Whether this `View` needs to rendered offscreen and composited with an alpha in order to preserve 100% correct colors and blending behavior. The default (`false`) falls back to drawing the component and its children with an alpha applied to the paint used to draw each element instead of rendering the full component offscreen and compositing it back with an alpha value. This default may be noticeable and undesired in the case where the `View` you are setting an opacity on has multiple overlapping elements (e.g. multiple overlapping `View`s, or text and a background).
707:Whether this `View` should render itself (and all of its children) into a single hardware texture on the GPU.
729:Whether this `View` should be rendered as a bitmap before compositing.
751:Whether this `View` should be focusable with a non-touch input device, eg. receive focus with a hardware keyboard.

keyboard.md
131:Whether the keyboard is last known to be visible.

alert.md
232:| isPreferred <div class="label ios">iOS</div> | boolean                                        | Whether button should be emphasized, on Android this property will be ignored. |

flatlist.md
781:- 'animated' (boolean) - Whether the list should do an animation while scrolling. Defaults to `true`.
808:- 'animated' (boolean) - Whether the list should do an animation while scrolling. Defaults to `true`.
837:- 'animated' (boolean) - Whether the list should do an animation while scrolling. Defaults to `true`.
863:- 'animated' (boolean) - Whether the list should do an animation while scrolling. Defaults to `true`.

pressable.md
150:Whether the press behavior is disabled.

progressbarandroid.md
67:Whether to show the ProgressBar (true, the default) or hide it (false).

animated.md
215:- `isInteraction`: Whether or not this animation creates an "interaction handle" on the `InteractionManager`. Default true.
233:- `isInteraction`: Whether or not this animation creates an "interaction handle" on the `InteractionManager`. Default true.
270:- `isInteraction`: Whether or not this animation creates an "interaction handle" on the `InteractionManager`. Default true.

activityindicator.md
50:Whether to show the indicator (`true`) or hide it (`false`).
70:Whether the indicator should hide when not animating.

virtualizedlist.md
661:- `'animated'` (boolean) - Whether the list should do an animation while scrolling. Defaults to `true`.
```

**Comment by lukasjengo** [comment]
Got it. 
I think originally I just wanted to change this sentence [here](https://github.com/facebook/react-native-website/pull/3801/files#diff-05c4f169cc200892422af8dc6202fb2d627a17ba727cdf8f125123e860c968adR445).
Change it to "whether this `View` needs to **be** rendered". Add the "be: to the sentence because it was lacking, but then I started to see the "whether + noun" pattern elsewhere, which seemed a bit off compared to "verb + whether + noun" :D

**Comment by MaheshaBhat** [comment]
@cortinico 
[https://reactnative.dev/architecture/render-pipeline](url) 
in the above doc **mount** phase has 3 stages but in the given example **Tree Diffing** is kept under **commit** phase, I think it needs to be corrected
Please correct this otherwise it will confuses the readers

**Comment by cortinico** [comment]
> in the above doc **mount** phase has 3 stages but in the given example **Tree Diffing** is kept under **commit** phase, I think it needs to be corrected.

cc @sammy-SC

**Comment by sammy-SC** [comment]
yes, that seems wrong. @MaheshaBhat good find! 

I will fix it in https://github.com/facebook/react-native-website/pull/3826 (I still need to read through the doc to make sure it fits within the new section).

**Comment by cortinico** [comment]
Closed by https://github.com/facebook/react-native-website/pull/3826

**Pull request closed without merging**
