### PR TITLE
Fix: img import from /docs/assets to /website/static/docs/assets 

### PR DESCRIPTION
**Pull request by khali70**
androidstudioavdimg

## Description
fix some img miss import 
Screenshot from 2021-07-09 16-50-42

> since issue is so simple i don't open Issue  

**edited**
Browser : *google chrome Version 91.0.4472.114 (Official Build) (64-bit)*
at pages
- *https://github.com/facebook/react-native-website/blob/master/docs/_getting-started-linux-android.md*
- *https://github.com/facebook/react-native-website/blob/master/docs/_getting-started-macos-android.md*
- *https://github.com/facebook/react-native-website/blob/master/docs/_getting-started-windows-android.md*

### CODE REVIEW

**Comment by khali70** [comment]
## future work 
### adding trouble shooting advice
adding advice to use `react-native doctor` in order to check if `react-native environment` is setup correctly

**Review by Simek — CHANGES_REQUESTED** [review]
Hi @khali70, can you elaborate more on your issue? Can you provide link to the page, your browser information etc.?

It looks like the image you are trying to change URL to image which currently works correctly on PROD, in both `next` nad `0.64` docs:

Screenshot 2021-07-10 094843

Also the reason why the deploy failed are incorrect image links after the changes:
```
4:56:58 PM: Error: Image static/website/static/img/AndroidAVDConfiguration.png used in ../docs/_getting-started-linux-android.md not found.
4:56:58 PM:     at async Promise.all (index 0)
4:56:58 PM: Error: Image static/website/static/img/AndroidAVDConfiguration.png used in ../docs/_getting-started-macos-android.md not found.
4:56:58 PM:     at async Promise.all (index 1)
4:56:58 PM: Error: Image static/website/static/img/AndroidAVDConfiguration.png used in ../docs/_getting-started-windows-android.md not found.
4:56:58 PM:     at async Promise.all (index 0)
4:56:58 PM: Client bundle compiled with errors therefore further build is impossible.
4:56:58 PM: error Command failed with exit code 1.
```

You can read more about how to Docusaurus handles assets in the docs:
* https://docusaurus.io/docs/markdown-features/assets

**Comment by khali70** [comment]
### as far as i understand 
the imgs need to move from 
#### GettingStartedAndroidStudioAVD.png **not found at** `/website/static/docs/assets`
```diff
# move or copy img from
- /website/static/img/AndroidAVDConfiguration.png
# to 
+ /website/docs/assets/GettingStartedAndroidStudioAVD.png
```

**Comment by Simek** [comment]
@khali70 Thank you for the information in the edited portion of the issue. 👍  

Unfortunately those pages should not be accessible, those are a partial pages, which content is used in the configuration wizard located at https://reactnative.dev/docs/environment-setup. On this page images are displayed correctly, at least on my machine.

I have already reported this issue to the Docusaurus team during the site migration. Hope they will be able to fix this issue soon. CC @slorber 

I will later take a look if this problem can be solved somehow on our side, for example by adding redirects to the server.

**Comment by slorber** [comment]
Will be fixed by https://github.com/facebook/docusaurus/pull/5173

**Pull request closed without merging**
